/**
 * Route Stops Ordering and Location Name Utilities
 * Fixes ordering, naming, and START/END positioning for route stops
 * 
 * CRITICAL RULES:
 * 1. START stop is ALWAYS first (index 0), distance = 0
 * 2. END stop is ALWAYS last (highest distance)
 * 3. Intermediate stops are sorted by distance ascending
 * 4. NO placeholder names like "Main Stop 3" should ever appear
 * 5. University names should be clean (e.g., "NED University Karachi")
 */

export interface Stop {
  id: string;
  name: string;
  lat: number;
  lng: number;
  distanceFromStart: number;
  type: string;
  isCustom?: boolean;
  isAutoGenerated?: boolean;
  order?: number;
}

/**
 * Known university patterns and their clean display names
 */
const UNIVERSITY_PATTERNS: Array<{ pattern: RegExp; displayName: string }> = [
  { pattern: /NED|National\s*Bank.*NED|NED\s*Branch/i, displayName: 'NED University Karachi' },
  { pattern: /FAST|NUCES|National\s*University.*Computer/i, displayName: 'FAST University Karachi' },
  { pattern: /IBA|Institute\s*of\s*Business/i, displayName: 'IBA University Karachi' },
  { pattern: /COMSATS|RCMS/i, displayName: 'COMSATS University Karachi' },
  { pattern: /Karachi\s*University|KU\b/i, displayName: 'Karachi University' },
  { pattern: /NED\s*University/i, displayName: 'NED University Karachi' },
  { pattern: /SZABIST/i, displayName: 'SZABIST Karachi' },
  { pattern: /Iqra\s*University/i, displayName: 'Iqra University Karachi' },
  { pattern: /Ziauddin/i, displayName: 'Ziauddin University' },
  { pattern: /AKU|Aga\s*Khan/i, displayName: 'Aga Khan University' },
  { pattern: /UBIT|UMT/i, displayName: 'UBIT' },
];

/**
 * Words/patterns that indicate placeholder or invalid names
 */
const PLACEHOLDER_PATTERNS = [
  /^stop\s*\d*$/i,
  /^main\s*stop\s*\d+$/i,
  /^route\s*stop\s*\d*$/i,
  /^loading\.?\.?\.?$/i,
  /^location\s*\d*$/i,
  /^unknown\s*(location)?$/i,
  /^near\s*$/i,
  /^fetching\s*(name|location)?\.?\.?\.?$/i,
  /^\d+\.\d+,?\s*\d+\.\d+$/, // Coordinates
  /^-?\d+\.\d+$/, // Single coordinate
  /^[0-9]+$/,  // Just numbers
  /^selected\s*location$/i,
  /^custom\s*stop$/i,
];

/**
 * Clean location names for display
 * Converts long addresses to clean, user-friendly names
 * Especially handles universities and common landmarks
 * 
 * RULES:
 * - University names → Clean format (e.g., "NED University Karachi")
 * - Bank/Branch names → Extract area name only
 * - Long addresses → Extract area/neighborhood
 * - Placeholder names → Return "Unknown Location" (will trigger geocoding)
 */
export function cleanLocationName(name: string | null | undefined): string {
  if (!name) return 'Unknown Location';

  const normalized = String(name).trim();

  // Check for placeholder patterns first
  for (const pattern of PLACEHOLDER_PATTERNS) {
    if (pattern.test(normalized)) {
      return 'Unknown Location';
    }
  }

  // Check for university patterns
  for (const { pattern, displayName } of UNIVERSITY_PATTERNS) {
    if (pattern.test(normalized)) {
      return displayName;
    }
  }

  // If it looks like coordinates, return unknown
  if (/^\d+\.\d+.*\d+\.\d+/.test(normalized)) {
    return 'Unknown Location';
  }

  // Split by comma for address parsing
  const parts = normalized.split(',').map(p => p.trim()).filter(p => p && p.length > 2);

  if (parts.length === 0) return 'Unknown Location';

  // Remove common noise words from first part
  const cleanFirstPart = (part: string) => {
    // Remove "National Bank of Pakistan", "Sui Gas Company" etc.
    if (/bank|branch|company|corporation|ltd|limited|pvt|private/i.test(part)) {
      return null; // Skip this part
    }
    return part;
  };

  // For very long addresses (e.g., "Bank Name, Branch, Area, City, Country")
  if (parts.length > 3) {
    // Skip bank/company names at the start
    for (let i = 0; i < parts.length; i++) {
      const cleaned = cleanFirstPart(parts[i]);
      if (cleaned) {
        // Look for area/neighborhood keywords
        if (/Block|Society|Extension|Phase|Scheme|Sector|Ward|Town|Colony|Garden|Park|Nagar|Abad|District/i.test(cleaned)) {
          return cleaned;
        }
      }
    }
    
    // Try second-to-last part (usually area/city)
    if (parts.length >= 2) {
      const areaCandidate = parts[parts.length - 2];
      if (areaCandidate && !/pakistan|sindh|karachi\s*division/i.test(areaCandidate)) {
        return areaCandidate;
      }
    }
    
    // Last resort: third part if exists
    if (parts.length >= 3 && parts[2]) {
      return parts[2];
    }
  }

  // For medium addresses (2-3 parts)
  if (parts.length >= 2) {
    const first = cleanFirstPart(parts[0]);
    if (first) {
      // If first part is short and second exists, combine
      if (first.length < 15 && parts[1]) {
        return `${first}, ${parts[1]}`;
      }
      return first;
    }
    // First part was a company name, use second
    return parts[1];
  }

  // Single part - use it if valid
  if (parts.length === 1) {
    const first = parts[0];
    // If it's a long company/bank name, just return generic
    if (/bank|branch|company/i.test(first) && first.length > 30) {
      return 'Unknown Location';
    }
    return first;
  }

  return normalized;
}

/**
 * Sort and order stops correctly
 * Ensures START is first, END is last, and all intermediate stops are by distance
 * 
 * CRITICAL: This function MUST ensure:
 * 1. Stop with type 'start' OR lowest distance → position 0
 * 2. Stop with type 'end' OR highest distance → last position
 * 3. All intermediate stops sorted by distanceFromStart ascending
 * 4. If no explicit types, use distance to determine START/END
 */
export function orderStopsCorrectly(stops: Stop[]): Stop[] {
  if (!stops || stops.length === 0) return [];
  if (stops.length === 1) return [{ ...stops[0], order: 0 }];

  // Create a working copy
  const workingStops = stops.map(s => ({ ...s }));

  // Find START stop (type='start' OR lowest distance)
  let startStop = workingStops.find(s => s.type === 'start');
  if (!startStop) {
    // No explicit start - find stop with lowest distance
    const sorted = [...workingStops].sort((a, b) => (a.distanceFromStart || 0) - (b.distanceFromStart || 0));
    startStop = sorted[0];
    startStop.type = 'start';
  }

  // Find END stop (type='end' OR highest distance)
  let endStop = workingStops.find(s => s.type === 'end' && s.id !== startStop!.id);
  if (!endStop) {
    // No explicit end - find stop with highest distance
    const sorted = [...workingStops].sort((a, b) => (b.distanceFromStart || 0) - (a.distanceFromStart || 0));
    endStop = sorted.find(s => s.id !== startStop!.id);
    if (endStop) {
      endStop.type = 'end';
    }
  }

  // Get intermediate stops (everything except START and END)
  const intermediateStops = workingStops.filter(s => 
    s.id !== startStop!.id && (!endStop || s.id !== endStop.id)
  );

  // Sort intermediate stops by distance ascending
  intermediateStops.sort((a, b) => (a.distanceFromStart || 0) - (b.distanceFromStart || 0));

  // Rebuild the array: START, intermediate (sorted), END
  const ordered: Stop[] = [];

  // Add START
  ordered.push({
    ...startStop!,
    order: 0,
    distanceFromStart: 0,
    type: 'start'
  });

  // Add intermediate stops
  intermediateStops.forEach((stop, idx) => {
    ordered.push({
      ...stop,
      order: idx + 1,
      type: 'route'
    });
  });

  // Add END (must be last!)
  if (endStop) {
    ordered.push({
      ...endStop,
      order: ordered.length,
      type: 'end'
    });
  }

  return ordered;
}

/**
 * Clean and validate stops
 * - Removes placeholder names
 * - Applies location name cleaning
 * - Ensures proper ordering
 * - Prevents duplicate locations
 */
export function cleanAndOrderStops(stops: Stop[]): Stop[] {
  if (!stops || stops.length === 0) return [];

  // Apply location name cleaning to all stops
  const cleanedStops = stops.map(stop => ({
    ...stop,
    name: cleanLocationName(stop.name)
  }));

  // Order correctly (START first, END last, intermediate by distance)
  const orderedStops = orderStopsCorrectly(cleanedStops);

  return orderedStops;
}

/**
 * Identify if a location is a START stop based on ride direction
 */
export function isStartLocation(locationName: string, universityName: string | null | undefined, isGoingToUniversity: boolean): boolean {
  const cleanName = cleanLocationName(locationName);
  const cleanUniName = universityName ? cleanLocationName(universityName) : '';

  // If going TO university, START should NOT be the university
  if (isGoingToUniversity) {
    return !cleanName.toLowerCase().includes(cleanUniName.toLowerCase());
  }

  // If LEAVING FROM university, START should be the university
  return cleanName.toLowerCase().includes(cleanUniName.toLowerCase());
}

/**
 * Detect ride direction based on start and end locations
 * Returns true if user is going TO university, false if leaving FROM university
 */
export function detectRideDirection(startLocation: string, endLocation: string, universityName: string | null | undefined): boolean {
  const cleanStart = cleanLocationName(startLocation).toLowerCase();
  const cleanEnd = cleanLocationName(endLocation).toLowerCase();
  const cleanUni = universityName ? cleanLocationName(universityName).toLowerCase() : '';

  if (!cleanUni) return true; // Default to "going to"

  // If end location is university, we're going TO it
  if (cleanEnd.includes(cleanUni)) {
    return true;
  }

  // If start location is university, we're leaving FROM it
  if (cleanStart.includes(cleanUni)) {
    return false;
  }

  return true; // Default
}

/**
 * Create minimal stops array with correct structure
 * Used as fallback when geocoding fails
 */
export function createFallbackStops(startLat: number, startLng: number, endLat: number, endLng: number, startName: string, endName: string): Stop[] {
  return [
    {
      id: `stop_${Date.now()}_0`,
      name: cleanLocationName(startName) || 'Start',
      lat: startLat,
      lng: startLng,
      distanceFromStart: 0,
      type: 'start',
      order: 0,
      isAutoGenerated: true
    },
    {
      id: `stop_${Date.now()}_1`,
      name: cleanLocationName(endName) || 'Destination',
      lat: endLat,
      lng: endLng,
      distanceFromStart: Math.round(
        Math.sqrt(
          Math.pow(endLat - startLat, 2) + Math.pow(endLng - startLng, 2)
        ) * 111 * 1000
      ), // Very rough estimate
      type: 'end',
      order: 1,
      isAutoGenerated: true
    }
  ];
}

/**
 * Remove duplicate/nearby stops
 * Prevents showing the same location twice
 */
export function removeDuplicateLocations(stops: Stop[]): Stop[] {
  const seen = new Map<string, Stop>();
  const seenNames = new Set<string>();

  for (const stop of stops) {
    const key = `${stop.lat.toFixed(5)},${stop.lng.toFixed(5)}`;
    
    // Normalize the name for comparison
    const normalizedName = (stop.name || '')
      .toLowerCase()
      .trim()
      .replace(/[,\-\.]/g, ' ')
      .replace(/\s+/g, ' ');

    // Skip if we've already seen this exact coordinate
    if (seen.has(key)) {
      continue;
    }

    // Skip if we've already seen this name (case-insensitive)
    // But allow "Start" and "End" to appear multiple times as they're special labels
    if (seenNames.has(normalizedName) && normalizedName !== 'start' && normalizedName !== 'end') {
      console.log(`[DEDUP] Skipping duplicate name: "${stop.name}"`);
      continue;
    }

    // Check if the name is too similar to any previously seen name (substring match)
    let isDuplicateName = false;
    for (const seenName of seenNames) {
      // Skip "start" and "end" checks
      if (seenName === 'start' || seenName === 'end') continue;
      
      // If names are identical or one contains the other (for compound names)
      if (normalizedName === seenName) {
        isDuplicateName = true;
        break;
      }

      // Check for substring matches (e.g., "Shahrah-e-Faisal" appears twice)
      // But require both names to be substantial (> 4 chars) to avoid false positives
      if (normalizedName.length > 4 && seenName.length > 4) {
        if (normalizedName.includes(seenName) || seenName.includes(normalizedName)) {
          isDuplicateName = true;
          console.log(`[DEDUP] Skipping similar name: "${stop.name}" is similar to previously seen name`);
          break;
        }
      }

      // Check if main parts match (first substantive word)
      const currentParts = normalizedName.split(/[\s,]+/).filter(p => p.length > 2);
      const seenParts = seenName.split(/[\s,]+/).filter(p => p.length > 2);
      
      if (currentParts.length > 0 && seenParts.length > 0 && currentParts[0] === seenParts[0]) {
        // Same main part (e.g., both start with "National")
        // Skip if names are long enough to be meaningful
        if (normalizedName.length > 6 && seenName.length > 6) {
          isDuplicateName = true;
          console.log(`[DEDUP] Skipping similar main part: "${stop.name}" has same main part as previous stop`);
          break;
        }
      }
    }

    if (isDuplicateName) {
      continue;
    }

    // Add this stop
    seen.set(key, stop);
    seenNames.add(normalizedName);
  }

  return Array.from(seen.values());
}

/**
 * Validate stop has a real name (not placeholder)
 * Returns true if the name is a placeholder that needs resolution
 */
export function isPlaceholderName(name: string | null | undefined): boolean {
  if (!name) return true;

  const normalized = String(name).trim().toLowerCase();

  // Empty or very short names
  if (normalized.length < 2) return true;

  // Check for all placeholder patterns
  const placeholderPatterns = [
    /^stop\s*\d*$/,
    /^main\s*stop\s*\d+$/,
    /^route\s*stop\s*\d*$/,
    /^route\s*point\s*\([\d.]+km\)$/,  // "Route Point (X.Xkm)" fallback
    /^\d+\.?\d*\s*km\s*from\s*start$/i,  // "X.Xkm from start" fallback
    /^loading\.?\.?\.?$/,
    /^location\s*\d*$/,
    /^unknown\s*(location)?$/,
    /^near\s*$/,
    /^fetching\s*(name|location)?\.?\.?\.?$/,
    /^\d+\.\d+,?\s*\d+\.\d+$/, // Coordinates
    /^-?\d+\.\d+$/, // Single coordinate
    /^[0-9]+$/,  // Just numbers
    /^selected\s*location$/,
    /^custom\s*stop$/,
  ];

  for (const pattern of placeholderPatterns) {
    if (pattern.test(normalized)) {
      return true;
    }
  }

  // Check if it's just "km from start" or similar
  if (/km from start|miles|distance/i.test(normalized)) {
    return true;
  }

  // Don't treat "Start" and "End" as placeholders if they're at correct positions
  // (they might be legitimate fallback names)
  return false;
}

/**
 * Get university display name for START/END labels
 */
export function getUniversityDisplayName(university: string | null | undefined): string {
  if (!university) return '';

  const uni = String(university).toLowerCase();

  if (uni.includes('ned')) return 'NED University';
  if (uni.includes('fast')) return 'FAST University';
  if (uni.includes('karachi') || uni.includes('uok')) return 'Karachi University';
  if (uni.includes('iba')) return 'IBA University';
  if (uni.includes('comsats') || uni.includes('rcms')) return 'COMSATS University';
  if (uni.includes('iqra')) return 'Iqra University';
  if (uni.includes('aku')) return 'AKU University';
  if (uni.includes('ziauddin')) return 'Ziauddin University';

  return university;
}
