import type { Timestamp } from 'firebase/firestore';

export interface UserProfile {
  uid: string;
  email: string;
  fullName: string;
  university: 'ned' | 'fast';
  gender: 'male' | 'female';
  contactNumber?: string;
  transport?: 'car' | 'bike';
  bio?: string;
  createdAt: Timestamp;
  // University email verification
  universityEmail?: string; // @nu.edu.pk or @cloud.neduet.edu.pk
  universityEmailVerified?: boolean;
  universityEmailVerifiedAt?: Timestamp;
  // ID verification (e.g., CNIC or Student ID)
  idVerified?: boolean;
  idVerifiedAt?: Timestamp;
  // Computed field: true if both email + ID verified
  isVerified?: boolean;
  // Password rate limiting
  passwordChangeCount?: number;
  passwordChangeWindowStart?: number;
  
  // ===== RIDE CANCELLATION TRACKING =====
  // Track participation and cancellation metrics
  totalParticipations?: number; // Total rides offered or booked
  totalCancellations?: number; // Total times cancelled (any status)
  lateCancellations?: number; // Cancellations after CONFIRMED status
  lastCancellationAt?: Timestamp; // When user last cancelled a ride
  
  // ===== ABUSE PREVENTION =====
  // Auto-lock account if cancellation rate exceeds 35% (after 3+ participations)
  accountLockUntil?: Timestamp; // Account locked until this timestamp
  // Cooldown period after 3 late cancellations
  cooldownUntil?: Timestamp; // User cannot cancel again until this time
}

// Canonical user profile used for new hierarchical storage under
// `universities/{univ}/users/{uid}`. We keep optional legacy fields
// to avoid breaking UI that still reads them, but the minimal required
// shape is defined here.
export interface CanonicalUserProfile {
  uid: string;
  name: string; // display name / short name
  email: string | null;
  university: 'ned' | 'fast';
  role: 'driver' | 'passenger';
  createdAt: Timestamp;
  // Optional legacy-compatible fields
  fullName?: string;
  gender?: 'male' | 'female';
  contactNumber?: string;
  transport?: 'car' | 'bike';
  // University email verification
  universityEmail?: string;
  universityEmailVerified?: boolean;
  universityEmailVerifiedAt?: Timestamp;
  // ID verification
  idVerified?: boolean;
  idVerifiedAt?: Timestamp;
  // Computed field: true if both email + ID verified
  isVerified?: boolean;
}

export interface Ride {
  id: string;
  driverId: string;
  from: string;
  to: string;
  departureTime: Timestamp;
  transportMode: 'car' | 'bike';
  price: number;
  totalSeats: number;
  availableSeats: number;
  genderAllowed: 'male' | 'female' | 'both';
  status: 'active' | 'full' | 'completed' | 'cancelled';
  route: { lat: number, lng: number }[];
  stops?: { name?: string; lat: number; lng: number; distanceFromStart?: number; type?: string; isCustom?: boolean; isAutoGenerated?: boolean }[];
  routePolyline?: string;
  distanceKm?: number;
  createdAt: Timestamp;
  driverInfo: {
    fullName: string;
    gender: 'male' | 'female';
    contactNumber?: string;
    transport?: 'car' | 'bike';
    universityEmailVerified?: boolean;
    idVerified?: boolean;
    isVerified?: boolean;
  };
  
  // ===== CANCELLATION FIELDS =====
  // When ride was cancelled by driver
  cancelledAt?: Timestamp;
  // ID of user who cancelled (driver)
  cancelledBy?: string;
  // Reason for cancellation
  cancellationReason?: string;
  // Runtime: passengers who have confirmed booking (used during confirmation flow)
  confirmedPassengers?: string[];
}

export interface Booking {
  id: string;
  rideId: string;
  driverId: string;
  passengerId: string;
  status: 'pending' | 'accepted' | 'rejected' | 'CONFIRMED' | 'declined' | 'CANCELLED';
  price?: number;
  pickupPlaceName?: string;
  createdAt: Timestamp;
  ride?: Ride; // Denormalized data for easier access
  passengerDetails?: UserProfile;
  driverDetails?: UserProfile;
  pickupPoint?: { lat: number, lng: number };
  
  // ===== CANCELLATION FIELDS =====
  // When booking was cancelled
  cancelledAt?: Timestamp;
  // ID of user who cancelled (driver or passenger)
  cancelledBy?: string;
  // Reason for cancellation
  cancellationReason?: string;
  // Whether this was a late cancellation (status was CONFIRMED when cancelled)
  isLateCancellation?: boolean;
}

// Ride Request status lifecycle for multi-request flow
export type RideRequestStatus =
  | 'PENDING'
  | 'ACCEPTED'
  | 'CONFIRMED'
  | 'CANCELLED'
  | 'AUTO_CANCELLED'
  | 'EXPIRED';

export interface RideRequest {
  id: string;
  rideId: string;
  driverId: string;
  passengerId: string;
  status: RideRequestStatus;
  createdAt: Timestamp;
  acceptedAt?: Timestamp;
  confirmedAt?: Timestamp;
  cancelledAt?: Timestamp;
  autoCancelledAt?: Timestamp;
  expiredAt?: Timestamp;
  expiresAt?: Timestamp; // countdown reference when ACCEPTED
  pickupPoint?: { lat: number; lng: number } | null;
  pickupPlaceName?: string | null;
  tripKey?: string; // grouping key to auto-cancel others on confirm
}

    