'use client';

import { useState, useCallback } from 'react';
import { useAuth } from '@/firebase';

interface Stop {
  id: string;
  name: string;
  lat: number;
  lng: number;
  distanceFromStart: number;
  type: string;
  isCustom?: boolean;
  isAutoGenerated?: boolean;
  order?: number;
}

export function useStops() {
  const { user } = useAuth();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  /**
   * Generate stops for a route
   */
  const generateStops = useCallback(
    async (
      routePolyline: string,
      routeDistance: number,
      from: string,
      to: string
    ): Promise<Stop[] | null> => {
      setLoading(true);
      setError(null);

      try {
        const response = await fetch('/api/rides/generate-stops', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            routePolyline,
            routeDistance,
            from,
            to,
          }),
        });

        if (!response.ok) {
          throw new Error('Failed to generate stops');
        }

        const data = await response.json();
        return data.stops || [];
      } catch (err: any) {
        const message = err.message || 'Failed to generate stops';
        setError(message);
        console.error('Error generating stops:', err);
        return null;
      } finally {
        setLoading(false);
      }
    },
    []
  );

  /**
   * Get stops for a ride
   */
  const getStops = useCallback(
    async (rideId: string, university: string = 'fast'): Promise<Stop[] | null> => {
      setLoading(true);
      setError(null);

      try {
        const response = await fetch(
          `/api/rides/${rideId}/stops?university=${university}`
        );

        if (!response.ok) {
          throw new Error('Failed to fetch stops');
        }

        const data = await response.json();
        return data.stops || [];
      } catch (err: any) {
        const message = err.message || 'Failed to fetch stops';
        setError(message);
        console.error('Error fetching stops:', err);
        return null;
      } finally {
        setLoading(false);
      }
    },
    []
  );

  /**
   * Update stops for a ride
   */
  const updateStops = useCallback(
    async (
      rideId: string,
      stops: Stop[],
      university: string = 'fast'
    ): Promise<boolean> => {
      setLoading(true);
      setError(null);

      if (!user) {
        setError('Not authenticated');
        setLoading(false);
        return false;
      }

      try {
        const token = await user.getIdToken();

        const response = await fetch(`/api/rides/${rideId}/stops?university=${university}`, {
          method: 'PUT',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${token}`,
          },
          body: JSON.stringify({ stops, university }),
        });

        if (!response.ok) {
          throw new Error('Failed to update stops');
        }

        return true;
      } catch (err: any) {
        const message = err.message || 'Failed to update stops';
        setError(message);
        console.error('Error updating stops:', err);
        return false;
      } finally {
        setLoading(false);
      }
    },
    [user]
  );

  /**
   * Add a custom stop to a ride
   */
  const addStop = useCallback(
    async (
      rideId: string,
      stop: Omit<Stop, 'id' | 'isCustom' | 'isAutoGenerated' | 'order'>,
      university: string = 'fast'
    ): Promise<Stop | null> => {
      setLoading(true);
      setError(null);

      if (!user) {
        setError('Not authenticated');
        setLoading(false);
        return null;
      }

      try {
        const token = await user.getIdToken();

        const response = await fetch(`/api/rides/${rideId}/stops`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${token}`,
          },
          body: JSON.stringify({ stop, university }),
        });

        if (!response.ok) {
          throw new Error('Failed to add stop');
        }

        const data = await response.json();
        return data.stop || null;
      } catch (err: any) {
        const message = err.message || 'Failed to add stop';
        setError(message);
        console.error('Error adding stop:', err);
        return null;
      } finally {
        setLoading(false);
      }
    },
    [user]
  );

  /**
   * Delete a stop from a ride
   */
  const deleteStop = useCallback(
    async (
      rideId: string,
      stopId: string,
      university: string = 'fast'
    ): Promise<boolean> => {
      setLoading(true);
      setError(null);

      if (!user) {
        setError('Not authenticated');
        setLoading(false);
        return false;
      }

      try {
        const token = await user.getIdToken();

        const response = await fetch(
          `/api/rides/${rideId}/stops?stopId=${stopId}&university=${university}`,
          {
            method: 'DELETE',
            headers: {
              Authorization: `Bearer ${token}`,
            },
          }
        );

        if (!response.ok) {
          throw new Error('Failed to delete stop');
        }

        return true;
      } catch (err: any) {
        const message = err.message || 'Failed to delete stop';
        setError(message);
        console.error('Error deleting stop:', err);
        return false;
      } finally {
        setLoading(false);
      }
    },
    [user]
  );

  return {
    generateStops,
    getStops,
    updateStops,
    addStop,
    deleteStop,
    loading,
    error,
  };
}
