import { NextRequest, NextResponse } from 'next/server';
import { getAuth } from 'firebase-admin/auth';
import { getFirestore } from 'firebase-admin/firestore';
import { initializeApp, cert } from 'firebase-admin/app';

// Initialize Firebase Admin
let adminApp: any;
try {
  const serviceAccount = JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT_JSON || '{}');
  adminApp = initializeApp({
    credential: cert(serviceAccount),
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  });
} catch (error) {
  console.warn('Firebase Admin not initialized');
}

const db = adminApp ? getFirestore(adminApp) : null;

/**
 * GET /api/rides/[rideId]/stops
 * Get all stops for a ride
 */
export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ rideId: string }> }
) {
  try {
    const { rideId } = await params;
    const { searchParams } = new URL(req.url);
    const university = searchParams.get('university') || 'fast';

    if (!db) {
      return NextResponse.json({ error: 'Database not initialized' }, { status: 500 });
    }

    const rideRef = db.collection('universities').doc(university).collection('rides').doc(rideId);
    const rideDoc = await rideRef.get();

    if (!rideDoc.exists) {
      return NextResponse.json({ error: 'Ride not found' }, { status: 404 });
    }

    const stops = rideDoc.data()?.stops || [];

    return NextResponse.json({
      success: true,
      stops: stops.sort((a: any, b: any) => a.order - b.order),
    });
  } catch (error: any) {
    console.error('Error fetching stops:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

/**
 * PUT /api/rides/[rideId]/stops
 * Update stops for a ride (creator only)
 */
export async function PUT(
  req: NextRequest,
  { params }: { params: Promise<{ rideId: string }> }
) {
  try {
    const { rideId } = await params;
    const { stops, university = 'fast' } = await req.json();

    if (!db) {
      return NextResponse.json({ error: 'Database not initialized' }, { status: 500 });
    }

    // Verify user is the ride creator
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const token = authHeader.replace('Bearer ', '');
    let uid: string;

    try {
      const decodedToken = await getAuth(adminApp).verifyIdToken(token);
      uid = decodedToken.uid;
    } catch (error) {
      return NextResponse.json({ error: 'Invalid token' }, { status: 401 });
    }

    const rideRef = db.collection('universities').doc(university).collection('rides').doc(rideId);
    const rideDoc = await rideRef.get();

    if (!rideDoc.exists) {
      return NextResponse.json({ error: 'Ride not found' }, { status: 404 });
    }

    const rideData = rideDoc.data();
    if (rideData?.createdBy !== uid && rideData?.driverId !== uid) {
      return NextResponse.json({ error: 'Only ride creator can update stops' }, { status: 403 });
    }

    // Validate stops
    const validatedStops = stops.map((stop: any, index: number) => ({
      id: stop.id || `stop_${Date.now()}_${index}`,
      name: stop.name,
      lat: parseFloat(stop.lat),
      lng: parseFloat(stop.lng),
      distanceFromStart: stop.distanceFromStart || 0,
      type: stop.type || 'custom',
      placeId: stop.placeId || null,
      isCustom: stop.isCustom || false,
      isAutoGenerated: stop.isAutoGenerated || false,
      order: index,
      createdAt: stop.createdAt || new Date().toISOString(),
      modifiedAt: new Date().toISOString(),
    }));

    // Update ride with new stops
    await rideRef.update({
      stops: validatedStops,
      stopsLastUpdated: new Date(),
    });

    return NextResponse.json({
      success: true,
      message: 'Stops updated successfully',
      stops: validatedStops,
    });
  } catch (error: any) {
    console.error('Error updating stops:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

/**
 * POST /api/rides/[rideId]/stops
 * Add a single custom stop
 */
export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ rideId: string }> }
) {
  try {
    const { rideId } = await params;
    const { stop, university = 'fast' } = await req.json();

    if (!db) {
      return NextResponse.json({ error: 'Database not initialized' }, { status: 500 });
    }

    // Verify user is the ride creator
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const token = authHeader.replace('Bearer ', '');
    let uid: string;

    try {
      const decodedToken = await getAuth(adminApp).verifyIdToken(token);
      uid = decodedToken.uid;
    } catch (error) {
      return NextResponse.json({ error: 'Invalid token' }, { status: 401 });
    }

    const rideRef = db.collection('universities').doc(university).collection('rides').doc(rideId);
    const rideDoc = await rideRef.get();

    if (!rideDoc.exists) {
      return NextResponse.json({ error: 'Ride not found' }, { status: 404 });
    }

    const rideData = rideDoc.data();
    if (rideData?.createdBy !== uid && rideData?.driverId !== uid) {
      return NextResponse.json({ error: 'Only ride creator can add stops' }, { status: 403 });
    }

    const currentStops = rideData?.stops || [];
    const newStop = {
      id: `stop_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
      name: stop.name,
      lat: parseFloat(stop.lat),
      lng: parseFloat(stop.lng),
      distanceFromStart: stop.distanceFromStart || 0,
      type: 'custom',
      placeId: null,
      isCustom: true,
      isAutoGenerated: false,
      order: currentStops.length,
      createdAt: new Date().toISOString(),
      modifiedAt: new Date().toISOString(),
    };

    const updatedStops = [...currentStops, newStop];

    await rideRef.update({
      stops: updatedStops,
      stopsLastUpdated: new Date(),
    });

    return NextResponse.json({
      success: true,
      message: 'Stop added successfully',
      stop: newStop,
    });
  } catch (error: any) {
    console.error('Error adding stop:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

/**
 * DELETE /api/rides/[rideId]/stops/[stopId]
 * Delete a specific stop
 */
export async function DELETE(
  req: NextRequest,
  { params }: { params: Promise<{ rideId: string }> }
) {
  try {
    const { rideId } = await params;
    const { searchParams } = new URL(req.url);
    const stopId = searchParams.get('stopId');
    const university = searchParams.get('university') || 'fast';

    if (!stopId) {
      return NextResponse.json({ error: 'stopId required' }, { status: 400 });
    }

    if (!db) {
      return NextResponse.json({ error: 'Database not initialized' }, { status: 500 });
    }

    // Verify user is the ride creator
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const token = authHeader.replace('Bearer ', '');
    let uid: string;

    try {
      const decodedToken = await getAuth(adminApp).verifyIdToken(token);
      uid = decodedToken.uid;
    } catch (error) {
      return NextResponse.json({ error: 'Invalid token' }, { status: 401 });
    }

    const rideRef = db.collection('universities').doc(university).collection('rides').doc(rideId);
    const rideDoc = await rideRef.get();

    if (!rideDoc.exists) {
      return NextResponse.json({ error: 'Ride not found' }, { status: 404 });
    }

    const rideData = rideDoc.data();
    if (rideData?.createdBy !== uid && rideData?.driverId !== uid) {
      return NextResponse.json({ error: 'Only ride creator can delete stops' }, { status: 403 });
    }

    const currentStops = rideData?.stops || [];
    const filteredStops = currentStops
      .filter((s: any) => s.id !== stopId)
      .map((s: any, index: number) => ({
        ...s,
        order: index,
      }));

    await rideRef.update({
      stops: filteredStops,
      stopsLastUpdated: new Date(),
    });

    return NextResponse.json({
      success: true,
      message: 'Stop deleted successfully',
    });
  } catch (error: any) {
    console.error('Error deleting stop:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
