'use client';

import React, { useState, useCallback, useRef, Suspense } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { MapPin, Plus, X, Edit2, Loader2, MousePointer2 } from 'lucide-react';
import { MapContainer, TileLayer, Marker, Popup, Polyline, useMapEvents } from '@/components/map';
import L from 'leaflet';
import { isPointNearPolyline, haversine, type LatLng } from '@/lib/route';
import { deduplicateByName } from '@/lib/stopFiltering';
import { detectUniversityFromString } from '@/lib/universities';

interface Stop {
  id: string;
  name: string;
  lat: number;
  lng: number;
  distanceFromStart: number;
  type: string;
  isCustom: boolean;
  isAutoGenerated: boolean;
  order: number;
}

interface StopsViewerProps {
  stops: Stop[];
  routePolyline?: string;
  routeCoordinates?: LatLng[];
  isCreator?: boolean;
  onUpdateStops?: (stops: Stop[]) => Promise<void>;
  triggerText?: string;
  onRequestRide?: () => void;
  university?: string;  // ===== NEW: Display university name =====
}

export default function StopsViewer({
  stops: initialStops,
  routePolyline,
  routeCoordinates,
  isCreator = false,
  onUpdateStops,
  triggerText = 'View Stops',
  onRequestRide,
  university,  // ===== NEW: Accept university prop =====
}: StopsViewerProps) {
  // Helper function to get the display university name
  const getUniversityDisplay = () => {
    if (university) {
      return university === 'fast' ? '🏫 FAST University' : university === 'ned' ? '🏫 NED University' : `🏫 ${university}`;
    }
    // Try to detect from first stop name
    if (initialStops.length > 0) {
      const detectedUni = detectUniversityFromString(initialStops[0].name);
      if (detectedUni === 'fast') return '🏫 FAST University';
      if (detectedUni === 'ned') return '🏫 NED University';
    }
    return null; // Return null instead of 'Your University'
  };

  const universityDisplay = getUniversityDisplay();

  // ===== FIX: Deduplicate stops by name to prevent duplicates like 'Shahrah-e-Faisal' appearing twice =====
  const [stops, setStops] = useState<Stop[]>(() => {
    // Remove consecutive duplicate names
    const deduped: Stop[] = [];
    let lastName = '';
    for (const stop of initialStops) {
      if (stop.name !== lastName) {
        deduped.push(stop);
        lastName = stop.name;
      }
    }
    return deduped;
  });
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editingName, setEditingName] = useState('');
  const [showAddStop, setShowAddStop] = useState(false);
  const [newStopName, setNewStopName] = useState('');
  const [isSaving, setIsSaving] = useState(false);
  const [isGeocodingStop, setIsGeocodingStop] = useState(false);
  const [geocodingError, setGeocodingError] = useState<string | null>(null);
  const [mapSelectionMode, setMapSelectionMode] = useState(false);
  const [selectedMapPoint, setSelectedMapPoint] = useState<LatLng | null>(null);
  const [selectedPlaceName, setSelectedPlaceName] = useState<string | null>(null);
  const [isFetchingNames, setIsFetchingNames] = useState(false);

  // Fetch names for stops that don't have meaningful names
  React.useEffect(() => {
    const fetchMissingNames = async () => {
      // Check if any stops need names fetched (have generic names like "Stop 1", "Stop 2", empty, or coordinates)
      const stopsNeedingNames = stops.filter(stop => 
        !stop.name || 
        /^(Stop|Location|Loading)\s*\d+$/i.test(stop.name.trim()) ||
        stop.name.trim().length === 0 ||
        /^\d+\.\d+,\s*\d+\.\d+$/.test(stop.name.trim()) // Match coordinate patterns like "24.8607, 67.0011"
      );

      if (stopsNeedingNames.length === 0 || isFetchingNames) return;

      console.log('Fetching names for', stopsNeedingNames.length, 'stops without meaningful names');
      setIsFetchingNames(true);

      try {
        const updatedStops = [...stops];
        
        for (let i = 0; i < stopsNeedingNames.length; i++) {
          const stop = stopsNeedingNames[i];
          const stopIndex = stops.findIndex(s => s.id === stop.id);
          
          if (stopIndex === -1) continue;

          try {
            await new Promise(resolve => setTimeout(resolve, i * 150)); // Rate limiting
            
            const res = await fetch(`/api/nominatim/reverse?lat=${stop.lat}&lon=${stop.lng}`);
            if (res.ok) {
              const data = await res.json();
              if (data.display_name) {
                // Extract meaningful name from display_name
                const parts = data.display_name.split(',').map((p: string) => p.trim());
                let shortName = parts[0];
                
                // Improve name extraction for better readability
                if (data.address) {
                  const area = data.address.neighbourhood || data.address.suburb || data.address.city_district;
                  const road = data.address.road || data.address.residential || data.address.pedestrian;
                  
                  if (road && area) {
                    shortName = `${road}, ${area}`;
                  } else if (road) {
                    shortName = road;
                  } else if (area) {
                    shortName = area;
                  } else if (parts.length > 1 && (/^\d+[a-z]?$/.test(shortName.trim()))) {
                    shortName = `${parts[0]}, ${parts[1]}`;
                  } else if (shortName.length < 3 && parts[1]?.length > 2) {
                    shortName = `${parts[0]}, ${parts[1]}`;
                  }
                }
                
                // Final validation - ensure name is not empty or coordinates
                if (shortName && shortName.length > 2 && !/^\d+\.\d+/.test(shortName)) {
                  updatedStops[stopIndex] = { ...updatedStops[stopIndex], name: shortName };
                  console.log(`Fetched name for stop ${stopIndex + 1}:`, shortName);
                } else {
                  // Fallback to a generic but informative name
                  updatedStops[stopIndex] = { ...updatedStops[stopIndex], name: `Stop ${stopIndex + 1}` };
                }
              }
            }
          } catch (error) {
            console.error(`Failed to fetch name for stop at index ${stopIndex}:`, error);
            // Ensure we at least have a generic name
            if (!updatedStops[stopIndex].name || updatedStops[stopIndex].name.trim().length === 0) {
              updatedStops[stopIndex] = { ...updatedStops[stopIndex], name: `Stop ${stopIndex + 1}` };
            }
          }
        }
        
        // Remove consecutive duplicate names (e.g., "National Highway" appearing multiple times)
        const deduplicatedStops = deduplicateByName(updatedStops);
        
        setStops(deduplicatedStops);
        console.log('Finished fetching stop names. Final count after deduplication:', deduplicatedStops.length);
      } catch (error) {
        console.error('Error fetching stop names:', error);
      } finally {
        setIsFetchingNames(false);
      }
    };

    fetchMissingNames();
  }, [initialStops]); // Re-run if initialStops change

  const handleRemoveStop = (id: string) => {
    setStops(stops.filter((s) => s.id !== id));
  };

  const handleRenameStop = (id: string, newName: string) => {
    setStops(
      stops.map((s) => (s.id === id ? { ...s, name: newName } : s))
    );
    setEditingId(null);
  };

  const handleAddStopFromMap = async (lat: number, lng: number) => {
    setIsGeocodingStop(true);
    setGeocodingError(null);

    try {
      // Reverse geocode to get the name
      const response = await fetch(`/api/nominatim/reverse?lat=${lat}&lon=${lng}`);
      const data = await response.json();

      const displayName = data.display_name || 'Custom Stop';
      // Import the extractMeaningfulStopName function
      const parts = displayName.split(',').map((p: string) => p.trim());
      let shortName = parts[0];
      
      // Extract meaningful name
      if (parts.length > 1 && (/^\d+[a-z]?$/.test(shortName.trim()))) {
        shortName = `${parts[0]}, ${parts[1]}`;
      } else if (shortName.length < 3 && parts[1]?.length > 2) {
        shortName = `${parts[0]}, ${parts[1]}`;
      }

      // Calculate distance from starting point
      const startPoint = stops.length > 0 ? stops[0] : (routeCoordinates && routeCoordinates.length > 0 ? routeCoordinates[0] : null);
      let distanceFromStart = 0;

      if (startPoint) {
        distanceFromStart = haversine(startPoint, { lat, lng });
      }

      const newStop: Stop = {
        id: `stop_${Date.now()}`,
        name: shortName,
        lat,
        lng,
        distanceFromStart,
        type: 'custom',
        isCustom: true,
        isAutoGenerated: false,
        order: stops.length,
      };

      // Add the new stop between START and END (keep fixed START/END positions)
      // Find actual START and END markers by type, not just position
      const startStop = stops.find(s => s.type === 'start' || s.type === 'fixed' && s.order === 0);
      const endStop = stops.find(s => s.type === 'end' || s.type === 'fixed' && stops.indexOf(s) === stops.length - 1);
      
      if (startStop && endStop && stops.length > 1) {
        // Both START and END exist - insert new stop between them
        const middleStops = stops.filter(s => s !== startStop && s !== endStop);
        
        // Sort middle stops + new stop by distance
        const stopsToSort = [...middleStops, newStop].sort((a, b) => a.distanceFromStart - b.distanceFromStart);
        
        // Reconstruct: [START, ...sorted middle stops, END]
        const updatedStops = [startStop, ...stopsToSort, endStop];
        const sortedStops = updatedStops.map((stop, idx) => ({ ...stop, order: idx }));
        setStops(sortedStops);
      } else if (stops.length > 0) {
        // Only START exists or no clear END - add new stop and sort by distance
        const updatedStops = [...stops, newStop].sort((a, b) => a.distanceFromStart - b.distanceFromStart);
        const sortedStops = updatedStops.map((stop, idx) => ({ ...stop, order: idx }));
        setStops(sortedStops);
      } else {
        // No stops exist, just add the new stop
        setStops([{ ...newStop, order: 0 }]);
      }
      
      setMapSelectionMode(false);
      setSelectedMapPoint(null);
    } catch (error) {
      console.error('Reverse geocoding error:', error);
      setGeocodingError('Failed to get location name. Please try again.');
    } finally {
      setIsGeocodingStop(false);
    }
  };

  const handleAddStop = async () => {
    if (!newStopName.trim()) return;

    setIsGeocodingStop(true);
    setGeocodingError(null);

    try {
      // Geocode the stop name to get coordinates
      const response = await fetch(`/api/nominatim/search?q=${encodeURIComponent(newStopName)}&limit=1`);
      const data = await response.json();

      if (!Array.isArray(data) || data.length === 0) {
        setGeocodingError('Location not found. Please try a different name.');
        setIsGeocodingStop(false);
        return;
      }

      const location = data[0];
      const lat = parseFloat(location.lat);
      const lng = parseFloat(location.lon);

      // Validate the stop is on the route
      if (routeCoordinates && routeCoordinates.length > 0) {
        const isOnRoute = isPointNearPolyline({ lat, lng }, routeCoordinates, 500);
        if (!isOnRoute) {
          setGeocodingError('This location is not on the route. Please select a location along your route.');
          setIsGeocodingStop(false);
          return;
        }
      }

      // Calculate distance from starting point (first stop or route start)
      const startPoint = stops.length > 0 ? stops[0] : (routeCoordinates && routeCoordinates.length > 0 ? routeCoordinates[0] : null);
      let distanceFromStart = 0;

      if (startPoint) {
        distanceFromStart = haversine(startPoint, { lat, lng });
      }

      const newStop: Stop = {
        id: `stop_${Date.now()}`,
        name: location.display_name.split(',')[0] || newStopName,
        lat,
        lng,
        distanceFromStart,
        type: 'custom',
        isCustom: true,
        isAutoGenerated: false,
        order: stops.length,
      };

      // Add the new stop between START and END (keep fixed START/END positions)
      // Find actual START and END markers by type, not just position
      const startStop = stops.find(s => s.type === 'start' || s.type === 'fixed' && s.order === 0);
      const endStop = stops.find(s => s.type === 'end' || s.type === 'fixed' && stops.indexOf(s) === stops.length - 1);
      
      if (startStop && endStop && stops.length > 1) {
        // Both START and END exist - insert new stop between them
        const middleStops = stops.filter(s => s !== startStop && s !== endStop);
        
        // Sort middle stops + new stop by distance
        const stopsToSort = [...middleStops, newStop].sort((a, b) => a.distanceFromStart - b.distanceFromStart);
        
        // Reconstruct: [START, ...sorted middle stops, END]
        const updatedStops = [startStop, ...stopsToSort, endStop];
        const sortedStops = updatedStops.map((stop, idx) => ({ ...stop, order: idx }));
        setStops(sortedStops);
      } else if (stops.length > 0) {
        // Only START exists or no clear END - add new stop and sort by distance
        const updatedStops = [...stops, newStop].sort((a, b) => a.distanceFromStart - b.distanceFromStart);
        const sortedStops = updatedStops.map((stop, idx) => ({ ...stop, order: idx }));
        setStops(sortedStops);
      } else {
        // No stops exist, just add the new stop
        setStops([{ ...newStop, order: 0 }]);
      }
      
      setNewStopName('');
      setShowAddStop(false);
    } catch (error) {
      console.error('Geocoding error:', error);
      setGeocodingError('Failed to find location. Please try again.');
    } finally {
      setIsGeocodingStop(false);
    }
  };

  const handleSaveStops = async () => {
    if (!onUpdateStops) return;

    setIsSaving(true);
    try {
      await onUpdateStops(stops);
    } finally {
      setIsSaving(false);
    }
  };

  const formatDistance = (meters: number) => {
    if (meters < 1000) return `${meters}m`;
    return `${(meters / 1000).toFixed(1)}km`;
  };

  // Map click handler component
  function MapClickHandler() {
    useMapEvents({
      click: async (e) => {
        if (!mapSelectionMode || !routeCoordinates) return;
        
        const clickedPoint = { lat: e.latlng.lat, lng: e.latlng.lng };
        
        // Check if clicked point is near the route (within 500 meters)
        const isOnRoute = isPointNearPolyline(clickedPoint, routeCoordinates, 500);
        
        if (isOnRoute) {
          setSelectedMapPoint(clickedPoint);
          setSelectedPlaceName('Fetching location...');
          setGeocodingError(null);
          
          // Fetch place name
          try {
            const response = await fetch(`/api/nominatim/reverse?lat=${clickedPoint.lat}&lon=${clickedPoint.lng}`);
            const data = await response.json();
            const displayName = data.display_name || 'Unknown location';
            
            // Extract meaningful name
            const parts = displayName.split(',').map((p: string) => p.trim());
            let shortName = parts[0];
            
            if (parts.length > 1 && (/^\d+[a-z]?$/.test(shortName.trim()))) {
              shortName = `${parts[0]}, ${parts[1]}`;
            } else if (shortName.length < 3 && parts[1]?.length > 2) {
              shortName = `${parts[0]}, ${parts[1]}`;
            }
            
            setSelectedPlaceName(shortName);
          } catch (error) {
            console.error('Failed to fetch place name:', error);
            setSelectedPlaceName('Selected Location');
          }
        } else {
          setGeocodingError('Please click on or near the route line.');
          setSelectedMapPoint(null);
          setSelectedPlaceName(null);
        }
      },
    });
    return null;
  }

  // If no triggerText, show stops directly without dialog
  if (!triggerText) {
    return (
      <div className="flex flex-col w-full max-h-[80vh]">
        <DialogHeader className="flex-shrink-0">
          <DialogTitle>Route Stops ({stops.length})</DialogTitle>
        </DialogHeader>

        <div className="flex-1 overflow-y-auto space-y-4 pr-2">
          {/* Stops List */}
          <div className="space-y-2 max-h-[40vh] overflow-y-auto">
            {stops.length === 0 ? (
              <div className="text-center py-8 text-muted-foreground">
                No stops available for this route
              </div>
            ) : (
              stops.map((stop, index) => {
                const isFirstStop = index === 0;
                const isLastStop = index === stops.length - 1;
                const isFixedStop = isFirstStop || isLastStop;
                
                return (
                <div
                  key={stop.id}
                  className={`p-3 border rounded-lg flex items-center gap-3 ${isFixedStop ? 'bg-muted/30' : ''}`}
                >
                  <div className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-semibold ${
                    isFixedStop 
                      ? 'bg-amber-500 text-white' 
                      : 'bg-primary text-primary-foreground'
                  }`}>
                    {index + 1}
                  </div>

                  <div className="flex-1 min-w-0">
                    {editingId === stop.id && isCreator && !isFixedStop ? (
                      <div className="flex gap-2">
                        <Input
                          value={editingName || ''}
                          onChange={(e) => setEditingName(e.target.value)}
                          placeholder="Stop name"
                          className="text-sm"
                        />
                        <Button
                          size="sm"
                          onClick={() =>
                            handleRenameStop(stop.id, editingName)
                          }
                        >
                          Save
                        </Button>
                      </div>
                    ) : (
                      <div>
                        <div className="font-semibold text-sm flex items-center gap-2">
                          {stop.name}
                          {isFirstStop && (
                            <Badge className="text-xs" variant="secondary">START</Badge>
                          )}
                          {isLastStop && (
                            <Badge className="text-xs" variant="secondary">END</Badge>
                          )}
                        </div>
                        <div className="text-xs text-muted-foreground">
                          {formatDistance(stop.distanceFromStart)} from start
                          {(isFirstStop || isLastStop) && universityDisplay && (
                            <React.Fragment key={`uni-display-${stop.id}`}>
                              {' • '}
                              <span className="font-semibold text-primary bg-primary/10 px-2 py-0.5 rounded">
                                {universityDisplay}
                              </span>
                            </React.Fragment>
                          )}
                          {!isFixedStop && stop.type && ` • ${stop.type}`}
                          {isFixedStop && ' • Fixed'}
                        </div>
                      </div>
                    )}
                  </div>

                  <div className="flex items-center gap-2">
                    <Badge variant="outline" className="text-xs">
                      {stop.isAutoGenerated ? 'Auto' : 'Custom'}
                    </Badge>

                    {isCreator && !isFixedStop && (
                      <div className="flex gap-2">
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => {
                            setEditingId(stop.id);
                            setEditingName(stop.name);
                          }}
                        >
                          <Edit2 className="w-3 h-3" />
                        </Button>

                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => handleRemoveStop(stop.id)}
                        >
                          <X className="w-4 h-4 text-destructive" />
                        </Button>
                      </div>
                    )}
                  </div>
                </div>
              );
              })
            )}
          </div>

          {/* Add Stop Section (Creator Only) */}
          {isCreator && (
            <div className="border-t pt-4">
              {mapSelectionMode ? (
                <div className="space-y-3 p-3 border rounded-lg bg-blue-50">
                  <div className="flex items-center gap-2">
                    <MousePointer2 className="w-4 h-4 text-blue-600" />
                    <p className="text-sm font-medium text-blue-900">
                      Click on the route map below to select a stop location
                    </p>
                  </div>
                  {selectedMapPoint && selectedPlaceName && (
                    <div className="text-xs text-muted-foreground">
                      Selected: {selectedPlaceName}
                    </div>
                  )}
                  {geocodingError && (
                    <p className="text-sm text-destructive">{geocodingError}</p>
                  )}
                  <div className="flex gap-2">
                    <Button 
                      size="sm" 
                      onClick={() => selectedMapPoint && handleAddStopFromMap(selectedMapPoint.lat, selectedMapPoint.lng)}
                      disabled={!selectedMapPoint || isGeocodingStop}
                    >
                      {isGeocodingStop ? (
                        <>
                          <Loader2 className="w-3 h-3 mr-2 animate-spin" />
                          Adding...
                        </>
                      ) : (
                        'Add Selected Stop'
                      )}
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => {
                        setMapSelectionMode(false);
                        setSelectedMapPoint(null);
                        setSelectedPlaceName(null);
                        setGeocodingError(null);
                      }}
                      disabled={isGeocodingStop}
                    >
                      Cancel
                    </Button>
                  </div>
                </div>
              ) : showAddStop ? (
                <div className="space-y-3 p-3 border rounded-lg bg-slate-50">
                  <div className="space-y-2">
                    <Input
                      placeholder="Enter stop name or address (e.g., University Road, Main Market)"
                      value={newStopName || ''}
                      onChange={(e) => {
                        setNewStopName(e.target.value);
                        setGeocodingError(null);
                      }}
                      onKeyDown={(e) => {
                        if (e.key === 'Enter' && !isGeocodingStop) {
                          handleAddStop();
                        }
                      }}
                      disabled={isGeocodingStop}
                    />
                    {geocodingError && (
                      <p className="text-sm text-destructive">{geocodingError}</p>
                    )}
                    <p className="text-xs text-muted-foreground">
                      Stop will be automatically positioned and sorted by distance from start
                    </p>
                  </div>
                  <div className="flex gap-2">
                    <Button 
                      size="sm" 
                      onClick={handleAddStop}
                      disabled={isGeocodingStop || !newStopName.trim()}
                    >
                      {isGeocodingStop ? (
                        <>
                          <Loader2 className="w-3 h-3 mr-2 animate-spin" />
                          Finding location...
                        </>
                      ) : (
                        'Add Stop'
                      )}
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => {
                        setShowAddStop(false);
                        setNewStopName('');
                        setGeocodingError(null);
                      }}
                      disabled={isGeocodingStop}
                    >
                      Cancel
                    </Button>
                  </div>
                </div>
              ) : (
                <div className="flex gap-2">
                  <Button
                    variant="outline"
                    className="flex-1 gap-2"
                    onClick={() => setShowAddStop(true)}
                  >
                    <Plus className="w-4 h-4" />
                    Add by Name
                  </Button>
                  <Button
                    variant="outline"
                    className="flex-1 gap-2"
                    onClick={() => setMapSelectionMode(true)}
                    disabled={!routeCoordinates || routeCoordinates.length === 0}
                  >
                    <MousePointer2 className="w-4 h-4" />
                    Select on Map
                  </Button>
                </div>
              )}
            </div>
          )}

          {/* Save Changes */}
          {isCreator && onUpdateStops && (
            <Button
              type="button"
              onClick={handleSaveStops}
              disabled={isSaving}
              className="w-full"
            >
              {isSaving ? 'Saving...' : 'Save Changes'}
            </Button>
          )}

          {/* Map Preview */}
          {stops.length > 0 && routePolyline && (
            <div className="border rounded-lg overflow-hidden flex-shrink-0" style={{ height: '250px' }}>
              <Suspense fallback={<div className="h-full w-full flex items-center justify-center bg-slate-900/50"><div className="text-slate-400">Loading map...</div></div>}>
                <MapContainer
                  bounds={L.latLngBounds(
                    stops.map((s) => [s.lat, s.lng])
                  )}
                  style={{ height: '100%', width: '100%', cursor: mapSelectionMode ? 'crosshair' : 'grab' }}
                >
                <TileLayer
                  url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                  attribution='&copy; OpenStreetMap contributors'
                />

                <MapClickHandler />

                {/* Show route polyline */}
                {routeCoordinates && routeCoordinates.length > 0 && (
                  <Polyline
                    key="route-polyline"
                    positions={routeCoordinates.map(c => [c.lat, c.lng])}
                    color="#87CEEB"
                    weight={3}
                    opacity={0.7}
                    dashArray="5,5"
                  />
                )}

                {/* Show selected point marker */}
                {selectedMapPoint && mapSelectionMode && (
                  <Marker
                    position={[selectedMapPoint.lat, selectedMapPoint.lng]}
                    icon={L.divIcon({
                      className: '',
                      html: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 36" width="32" height="48">
                        <defs>
                          <filter id="shadow-selected" x="-50%" y="-50%" width="200%" height="200%">
                            <feGaussianBlur stdDeviation="2" />
                          </filter>
                        </defs>
                        <path d="M12 2C8 2 5 5 5 9c0 6 7 25 7 25s7-19 7-25c0-4-3-7-7-7z" fill="#ff9800" stroke="#ffffff" stroke-width="1.5" filter="url(#shadow-selected)" />
                        <circle cx="12" cy="9" r="3" fill="#ffffff" stroke="#ff9800" stroke-width="1.5" />
                      </svg>`,
                      iconSize: [32, 48],
                      iconAnchor: [16, 48],
                      popupAnchor: [0, -48],
                      tooltipAnchor: [0, -48],
                    })}
                  >
                    <Popup>Selected location</Popup>
                  </Marker>
                )}

                {stops.map((stop, idx) => (
                  <Marker
                    key={stop.id || `marker-${idx}`}
                    position={[stop.lat, stop.lng]}
                    icon={L.divIcon({
                      className: '',
                      html: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 36" width="32" height="48">
                        <defs>
                          <filter id="shadow-${idx}" x="-50%" y="-50%" width="200%" height="200%">
                            <feGaussianBlur stdDeviation="2" />
                          </filter>
                        </defs>
                        <path d="M12 2C8 2 5 5 5 9c0 6 7 25 7 25s7-19 7-25c0-4-3-7-7-7z" fill="${
                          idx === 0 ? '#16a34a' :  // Green for START
                          idx === stops.length - 1 ? '#2563eb' :  // Blue for END
                          stop.isAutoGenerated ? '#8b5cf6' : '#f59e0b'  // Purple for auto, Amber for custom
                        }" stroke="#ffffff" stroke-width="1.5" filter="url(#shadow-${idx})" />
                        <circle cx="12" cy="9" r="2.5" fill="#ffffff" />
                      </svg>`,
                      iconSize: [32, 48],
                      iconAnchor: [16, 48],
                      popupAnchor: [0, -48],
                      tooltipAnchor: [0, -48],
                    })}
                  >
                    <Popup>
                      <strong>{stop.name}</strong>
                      <br/>
                      {stop.isAutoGenerated ? 'Auto' : 'Custom'}
                    </Popup>
                  </Marker>
                ))}
              </MapContainer>
              </Suspense>
            </div>
          )}

          {/* ===== FIX: Show selected point and confirmation buttons when map selection is active =====*/}
          {mapSelectionMode && selectedMapPoint && selectedPlaceName && (
            <div className="p-3 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg">
              <div className="text-sm font-semibold mb-2">📍 Selected Location:</div>
              <div className="text-sm text-blue-900 dark:text-blue-100 mb-3 font-medium">{selectedPlaceName}</div>
              <div className="flex gap-2">
                <Button
                  size="sm"
                  onClick={() => {
                    // Add the selected point as a new stop
                    const newStop: Stop = {
                      id: `stop-${Date.now()}`,
                      name: selectedPlaceName,
                      lat: selectedMapPoint.lat,
                      lng: selectedMapPoint.lng,
                      distanceFromStart: 0,
                      type: 'map-selected',
                      isCustom: true,
                      isAutoGenerated: false,
                      order: stops.length,
                    };
                    setStops([...stops, newStop]);
                    setSelectedMapPoint(null);
                    setSelectedPlaceName(null);
                    setMapSelectionMode(false);
                  }}
                  className="flex-1"
                >
                  ✅ Add This Stop
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => {
                    setSelectedMapPoint(null);
                    setSelectedPlaceName(null);
                    setMapSelectionMode(false);
                  }}
                  className="flex-1"
                >
                  ✕ Cancel
                </Button>
              </div>
            </div>
          )}

        {/* Request Ride Button - for non-creators */}
        {!isCreator && onRequestRide && (
          <div className="flex gap-2 pt-4 border-t flex-shrink-0">
            <button
              onClick={onRequestRide}
              className="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded-md transition"
            >
              Request Ride
            </button>
          </div>
        )}
        </div>
      </div>
    );
  }

  // Show with trigger button in Dialog
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline" className="gap-2">
          <MapPin className="w-4 h-4" />
          {triggerText}
        </Button>
      </DialogTrigger>

      <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto z-[9999]">
        <DialogHeader>
          <DialogTitle>Route Stops ({stops.length})</DialogTitle>
        </DialogHeader>
        <p className="sr-only" id="stops-dialog-desc">Stops list and map preview for this route.</p>

        <div className="space-y-4">
          {/* Stops List */}
          <div className="space-y-2">
            {stops.length === 0 ? (
              <div className="text-center py-8 text-muted-foreground">
                No stops available for this route
              </div>
            ) : (
              stops.map((stop, index) => {
                const isFirstStop = index === 0;
                const isLastStop = index === stops.length - 1;
                const isFixedStop = isFirstStop || isLastStop;
                
                return (
                  <div
                    key={stop.id}
                    className={`p-3 border rounded-lg flex items-center gap-3 ${isFixedStop ? 'bg-muted/30' : ''}`}
                  >
                  <div className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-semibold ${
                    isFixedStop 
                      ? 'bg-amber-500 text-white' 
                      : 'bg-primary text-primary-foreground'
                  }`}>
                    {index + 1}
                  </div>

                  <div className="flex-1 min-w-0">
                    {editingId === stop.id && isCreator && !isFixedStop ? (
                      <div className="flex gap-2">
                        <Input
                          value={editingName || ''}
                          onChange={(e) => setEditingName(e.target.value)}
                          placeholder="Stop name"
                          className="text-sm"
                        />
                        <Button
                          size="sm"
                          onClick={() =>
                            handleRenameStop(stop.id, editingName)
                          }
                        >
                          Save
                        </Button>
                      </div>
                    ) : (
                      <div>
                        <div className="font-semibold text-sm flex items-center gap-2">
                          {stop.name}
                          {isFirstStop && (
                            <Badge className="text-xs" variant="secondary">START</Badge>
                          )}
                          {isLastStop && (
                            <Badge className="text-xs" variant="secondary">END</Badge>
                          )}
                        </div>
                        <div className="text-xs text-muted-foreground">
                          {formatDistance(stop.distanceFromStart)} from start
                          {(isFirstStop || isLastStop) && universityDisplay && (
                            <React.Fragment key={`uni-display-2-${stop.id}`}>
                              {' • '}
                              <span className="font-semibold text-primary bg-primary/10 px-2 py-0.5 rounded">
                                {universityDisplay}
                              </span>
                            </React.Fragment>
                          )}
                          {!isFixedStop && stop.type && ` • ${stop.type}`}
                          {isFixedStop && ' • Fixed'}
                        </div>
                      </div>
                    )}
                  </div>

                  <div className="flex items-center gap-2">
                    <Badge variant="outline" className="text-xs">
                      {stop.isAutoGenerated ? 'Auto' : 'Custom'}
                    </Badge>

                    {isCreator && !isFixedStop && (
                      <>
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => {
                            setEditingId(stop.id);
                            setEditingName(stop.name);
                          }}
                        >
                          <Edit2 className="w-4 h-4" />
                        </Button>
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => handleRemoveStop(stop.id)}
                        >
                          <X className="w-4 h-4" />
                        </Button>
                      </>
                    )}
                  </div>
                </div>
                );
              })
            )}
          </div>

          {/* Add Stop Section - only for creators */}
          {isCreator && (
            <div className="border rounded-lg p-4 space-y-3">
              <div className="font-semibold">Add Stop</div>
              {showAddStop ? (
                <div className="space-y-2">
                  <Input
                    value={newStopName}
                    onChange={(e) => setNewStopName(e.target.value)}
                    placeholder="Enter stop name"
                    className="text-sm"
                  />
                  <div className="flex gap-2">
                    <Button
                      size="sm"
                      onClick={handleAddStop}
                      disabled={isGeocodingStop}
                    >
                      {isGeocodingStop ? 'Searching...' : 'Search & Add'}
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => setShowAddStop(false)}
                    >
                      Cancel
                    </Button>
                  </div>
                  {geocodingError && (
                    <div className="text-xs text-red-600">{geocodingError}</div>
                  )}
                </div>
              ) : (
                <Button
                  size="sm"
                  className="gap-2"
                  onClick={() => setShowAddStop(true)}
                >
                  <Plus className="w-4 h-4" />
                  Search by Name
                </Button>
              )}
              <Button
                size="sm"
                variant="outline"
                className="w-full gap-2"
                onClick={() => setMapSelectionMode(!mapSelectionMode)}
              >
                <MousePointer2 className="w-4 h-4" />
                {mapSelectionMode ? 'Cancel Map Selection' : 'Select from Map'}
              </Button>
            </div>
          )}

          {/* Selected Location Confirmation - when map selection is active */}
          {mapSelectionMode && selectedMapPoint && selectedPlaceName && (
            <div className="bg-blue-50 dark:bg-blue-950 border border-blue-200 dark:border-blue-800 rounded-lg p-4 space-y-3">
              <div className="text-sm text-blue-900 dark:text-blue-100 mb-3 font-medium">{selectedPlaceName}</div>
              <div className="flex gap-2">
                <Button
                  size="sm"
                  className="flex-1"
                  onClick={() => {
                    const newStop = {
                      id: `stop-${Date.now()}`,
                      name: selectedPlaceName,
                      lat: selectedMapPoint.lat,
                      lng: selectedMapPoint.lng,
                      distanceFromStart: 0,
                      type: 'map-selected',
                      isCustom: true,
                      isAutoGenerated: false,
                      order: stops.length,
                    };
                    setStops([...stops, newStop]);
                    setSelectedMapPoint(null);
                    setSelectedPlaceName(null);
                    setMapSelectionMode(false);
                  }}
                >
                  ✅ Add This Stop
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => {
                    setSelectedMapPoint(null);
                    setSelectedPlaceName(null);
                    setMapSelectionMode(false);
                  }}
                  className="flex-1"
                >
                  ✕ Cancel
                </Button>
              </div>
            </div>
          )}

          {/* Map Display */}
          {routePolyline && routeCoordinates && routeCoordinates.length > 0 && (
            <div className="border rounded-lg overflow-hidden h-64">
              <Suspense fallback={<div className="h-full w-full flex items-center justify-center bg-slate-900/50"><div className="text-slate-400">Loading map...</div></div>}>
              <MapContainer
                bounds={L.latLngBounds(routeCoordinates as L.LatLngExpression[])}
                style={{ height: '100%', width: '100%' }}
              >
                <TileLayer
                  url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                  attribution='&copy; OpenStreetMap contributors'
                />
                <Polyline
                  positions={routeCoordinates as L.LatLngExpression[]}
                  color="#87CEEB"
                  weight={4}
                  opacity={0.8}
                />
                <MapClickHandler />
                {selectedMapPoint && (
                  <Marker position={[selectedMapPoint.lat, selectedMapPoint.lng] as L.LatLngExpression}>
                    <Popup>{selectedPlaceName || 'Selected Point'}</Popup>
                  </Marker>
                )}
                {stops.map((stop, idx) => (
                  <Marker key={stop.id || `marker-${idx}`} position={[stop.lat, stop.lng] as L.LatLngExpression}>
                    <Popup>{stop.name}</Popup>
                  </Marker>
                ))}
              </MapContainer>
              </Suspense>
            </div>
          )}

          {/* Request Ride Button - for non-creators */}
          {!isCreator && onRequestRide && (
            <div className="flex gap-2 pt-4 border-t">
              <button
                onClick={onRequestRide}
                className="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded-md transition"
              >
                Request Ride
              </button>
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
