'use client';

import React, { useState, useCallback, useRef, Suspense } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { MapPin, Plus, X, Edit2, Loader2, MousePointer2 } from 'lucide-react';
import { MapContainer, TileLayer, Marker, Popup, Polyline, Tooltip, useMapEvents } from '@/components/map';
import { isPointNearPolyline, haversine, type LatLng } from '@/lib/route';
import { deduplicateByName } from '@/lib/stopFiltering';
import { detectUniversityFromString } from '@/lib/universities';
import { cleanLocationName, orderStopsCorrectly, isPlaceholderName } from '@/lib/stopOrdering';

interface Stop {
  id: string;
  name: string;
  lat: number;
  lng: number;
  distanceFromStart: number;
  type: string;
  isCustom?: boolean;
  isAutoGenerated?: boolean;
  order?: number;
}

interface StopsViewerProps {
  stops: Stop[] | Record<string, Stop> | null | undefined;
  routePolyline?: string;
  routeCoordinates?: LatLng[];
  isCreator?: boolean;
  onUpdateStops?: (stops: Stop[]) => Promise<void>;
  triggerText?: string;
  onRequestRide?: () => void;
  university?: string;  // ===== NEW: Display university name =====
  getAuthToken?: () => Promise<string>;
}

function getBoundsFromPoints(points: Array<{ lat: number; lng: number }>): [[number, number], [number, number]] | undefined {
  if (!points || points.length === 0) return undefined;

  const valid = points.filter((point) => Number.isFinite(Number(point.lat)) && Number.isFinite(Number(point.lng)));
  if (valid.length === 0) return undefined;

  const lats = valid.map((point) => Number(point.lat));
  const lngs = valid.map((point) => Number(point.lng));

  return [
    [Math.min(...lats), Math.min(...lngs)],
    [Math.max(...lats), Math.max(...lngs)],
  ];
}

export default function StopsViewer({
  stops: initialStops,
  routePolyline,
  routeCoordinates,
  isCreator = false,
  onUpdateStops,
  triggerText = 'View Stops',
  onRequestRide,
  university,  // ===== NEW: Accept university prop =====
  getAuthToken,
}: StopsViewerProps) {
  const resolvingNamesRef = useRef(false);
  const requestedNameKeysRef = useRef<Set<string>>(new Set());

  const safeStringify = useCallback((value: any) => {
    try {
      const seen = new WeakSet();
      return JSON.stringify(value, (_key, val) => {
        if (val && typeof val === 'object') {
          if (seen.has(val)) return '[Circular]';
          seen.add(val);
        }
        return val;
      });
    } catch (err) {
      return '[Unserializable]';
    }
  }, []);

  const normalizeStopsInput = useCallback((raw: any): Stop[] => {
    if (!raw) return [];
    if (Array.isArray(raw)) return raw as Stop[];
    if (typeof raw === 'object') return Object.values(raw) as Stop[];
    return [];
  }, []);

  const getStopKey = (stop: Stop, index: number) => {
    return stop.id || `${stop.lat}-${stop.lng}-${index}`;
  };

  const needsNameLookup = (name: string | undefined | null) => {
    return isPlaceholderName(name);
  };

  const buildPlaceName = (data: any) => {
    try {
      const addr = data?.address || {};
      const landmark = addr.amenity || addr.shop || addr.building || addr.office || addr.tourism || addr.leisure || addr.historic;
      const road = addr.road || addr.street || addr.avenue || addr.boulevard || addr.highway || addr.path || addr.residential;
      const area = addr.neighbourhood || addr.suburb || addr.quarter || addr.city_district || addr.residential || addr.hamlet;
      const city = addr.city || addr.town || addr.village || addr.municipality;

      if (landmark) return area ? `${landmark}, ${area}` : landmark;
      if (road && area) return `${road}, ${area}`;
      if (road && city) return `${road}, ${city}`;
      if (area && city) return `${area}, ${city}`;
      if (area) return area;
      if (road) return road;
      if (city) return city;

      if (data?.display_name) {
        const parts = String(data.display_name)
          .split(',')
          .map((p: string) => p.trim())
          .filter((p: string) => p && !/^\d+$/.test(p) && p.length > 2);
        if (parts.length >= 2) return `${parts[0]}, ${parts[1]}`;
        if (parts.length === 1) return parts[0];
      }
    } catch (_) {}
    return 'Selected Location';
  };
  const normalizedInitialStops = normalizeStopsInput(initialStops);

  // Helper function to get the display university name
  const getUniversityDisplay = () => {
    if (university) {
      return university === 'fast' ? '🏫 FAST University' : university === 'ned' ? '🏫 NED University' : `🏫 ${university}`;
    }
    // Try to detect from first stop name
    if (normalizedInitialStops.length > 0) {
      const detectedUni = detectUniversityFromString(normalizedInitialStops[0].name);
      if (detectedUni === 'fast') return '🏫 FAST University';
      if (detectedUni === 'ned') return '🏫 NED University';
    }
    return null; // Return null instead of 'Your University'
  };

  const universityDisplay = getUniversityDisplay();

  // ===== Normalize and ORDER stops: preserve ALL stops =====
  const [stops, setStops] = useState<Stop[]>(() => {
    return orderStopsCorrectly(normalizedInitialStops);
  });
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editingName, setEditingName] = useState('');
  const [showAddStop, setShowAddStop] = useState(false);
  const [newStopName, setNewStopName] = useState('');
  const [isSaving, setIsSaving] = useState(false);
  const [isGeocodingStop, setIsGeocodingStop] = useState(false);
  const [geocodingError, setGeocodingError] = useState<string | null>(null);
  const [mapSelectionMode, setMapSelectionMode] = useState(false);
  const [selectedMapPoint, setSelectedMapPoint] = useState<LatLng | null>(null);
  const [selectedPlaceName, setSelectedPlaceName] = useState<string | null>(null);
  const [isFetchingNames, setIsFetchingNames] = useState(false);

  const stopsWithCoords = React.useMemo(() => {
    return stops.filter((s: any) => Number.isFinite(Number(s?.lat)) && Number.isFinite(Number(s?.lng)));
  }, [stops]);

  // Update stops when initialStops changes
  React.useEffect(() => {
    const normalizedStops = normalizeStopsInput(initialStops);
    console.log('[STOPS_VIEWER] Raw stops payload:', safeStringify(initialStops));
    console.log('[STOPS_VIEWER] Normalized stops:', safeStringify(normalizedStops));
    console.log('[STOPS_VIEWER] Updating state with', normalizedStops.length, 'stops');

    // Reset name lookup tracking so distance-based names can be re-resolved
    requestedNameKeysRef.current = new Set();
    resolvingNamesRef.current = false;

    // CRITICAL: Preserve ALL stops - do NOT deduplicate
    let orderedStops = orderStopsCorrectly(normalizedStops);
    
    // =====FIX: If only 1 or 2 stops and we have route coordinates, generate intermediate waypoints =====
    if ((orderedStops.length <= 2) && routeCoordinates && routeCoordinates.length > 10) {
      console.log('[STOPS_VIEWER] Generating intermediate waypoints from route polyline...');
      const numWaypoints = Math.min(Math.floor(routeCoordinates.length / 3), 5); // Create 3-5 intermediate stops
      const startStop = orderedStops.find(s => s.type === 'start');
      const endStop = orderedStops.find(s => s.type === 'end');
      
      if (startStop && endStop) {
        const intermediateStops: Stop[] = [];
        
        // Generate intermediate waypoints at intervals
        for (let i = 1; i <= numWaypoints; i++) {
          const index = Math.floor((routeCoordinates.length - 1) * (i / (numWaypoints + 1)));
          const coord = routeCoordinates[index];
          
          // Only add if it has valid coordinates
          if (coord && Number.isFinite(coord.lat) && Number.isFinite(coord.lng)) {
            intermediateStops.push({
              id: `waypoint-${i}`,
              name: `Stop ${i}`, // Will be resolved by geocoding
              lat: coord.lat,
              lng: coord.lng,
              distanceFromStart: 0,
              type: 'waypoint',
              isAutoGenerated: true,
              order: i,
            });
          }
        }
        
        // Combine: start + intermediate + end
        if (intermediateStops.length > 0) {
          orderedStops = [
            startStop,
            ...intermediateStops,
            endStop,
          ];
          console.log('[STOPS_VIEWER] Generated', intermediateStops.length, 'intermediate waypoints');
        }
      }
    }
    
    console.log('[STOPS_VIEWER] Ordered stops:', orderedStops.map((s, i) => `${i + 1}:${s.type}:"${s.name}"`).join(', '));

    setStops(orderedStops);
    setIsFetchingNames(false); // Reset fetching state
  }, [initialStops, normalizeStopsInput, safeStringify, routeCoordinates]);

  // Resolve placeholder/distance-based names to real places
  React.useEffect(() => {
    if (typeof window === 'undefined') return;
    if (resolvingNamesRef.current) return;

    const unresolved = stops
      .map((stop, index) => ({ stop, index, key: getStopKey(stop, index) }))
      .filter(({ stop }) => needsNameLookup(stop.name));

    // Limit to max 5 unresolved stops to prevent API overload
    if (unresolved.length === 0 || unresolved.length > 5) {
      if (unresolved.length > 5) {
        console.warn('[STOPS_VIEWER] Too many unresolved stops, skipping auto-resolve');
      }
      return;
    }

    resolvingNamesRef.current = true;
    setIsFetchingNames(true);

    (async () => {
      try {
        const updated = [...stops];
        const headers: HeadersInit = { 'Content-Type': 'application/json' };
        if (getAuthToken) {
          try {
            const token = await getAuthToken();
            if (token) headers['Authorization'] = `Bearer ${token}`;
          } catch (_) {}
        }

        // Process sequentially with delay to avoid rate limiting
        for (const item of unresolved) {
          if (requestedNameKeysRef.current.has(item.key)) continue;
          requestedNameKeysRef.current.add(item.key);
          
          try {
            const res = await fetch(`/api/nominatim/reverse?lat=${item.stop.lat}&lon=${item.stop.lng}`, {
              headers,
              signal: AbortSignal.timeout(10000)
            });
            if (res.ok) {
              const data = await res.json();
              const placeName = buildPlaceName(data);
              updated[item.index] = { ...updated[item.index], name: placeName };
            }
          } catch (err) {
            console.warn(`[STOPS_VIEWER] Failed to resolve stop ${item.index}:`, err);
          }
          
          // Add delay between requests
          await new Promise(r => setTimeout(r, 300));
        }

        setStops(updated);
      } finally {
        resolvingNamesRef.current = false;
        setIsFetchingNames(false);
      }
    })();
  }, [stops, getAuthToken]);

  const handleRemoveStop = (id: string) => {
    const filtered = stops.filter((s) => s.id !== id);
    // Re-order after removal to maintain proper START/END positions
    setStops(orderStopsCorrectly(filtered));
  };

  const handleRenameStop = (id: string, newName: string) => {
    setStops(
      stops.map((s) => (s.id === id ? { ...s, name: newName } : s))
    );
    setEditingId(null);
  };

  const handleAddStopFromMap = async (lat: number, lng: number) => {
    setIsGeocodingStop(true);
    setGeocodingError(null);

    try {
      // Reverse geocode to get the name
      const headers: HeadersInit = { 'Content-Type': 'application/json' };
      if (getAuthToken) {
        try {
          const token = await getAuthToken();
          if (token) headers['Authorization'] = `Bearer ${token}`;
        } catch (_) {}
      }
      const response = await fetch(`/api/nominatim/reverse?lat=${lat}&lon=${lng}`, { headers });
      const data = await response.json();

      const displayName = data.display_name || 'Custom Stop';
      // Import the extractMeaningfulStopName function
      const parts = displayName.split(',').map((p: string) => p.trim());
      let shortName = parts[0];
      
      // Extract meaningful name
      if (parts.length > 1 && (/^\d+[a-z]?$/.test(shortName.trim()))) {
        shortName = `${parts[0]}, ${parts[1]}`;
      } else if (shortName.length < 3 && parts[1]?.length > 2) {
        shortName = `${parts[0]}, ${parts[1]}`;
      }

      // Calculate distance from starting point
      const startPoint = stops.length > 0 ? stops[0] : (routeCoordinates && routeCoordinates.length > 0 ? routeCoordinates[0] : null);
      let distanceFromStart = 0;

      if (startPoint) {
        distanceFromStart = haversine(startPoint, { lat, lng });
      }
      
      // CRITICAL: Cap distance to ensure new stop never exceeds END stop distance
      // This prevents new stops from accidentally becoming the END stop
      const endStop = stops.find(s => s.type === 'end');
      if (endStop && endStop.distanceFromStart && distanceFromStart > endStop.distanceFromStart) {
        // Set distance slightly less than END to maintain ordering
        distanceFromStart = endStop.distanceFromStart - 10; // 10 meters before END
      }

      const newStop: Stop = {
        id: `stop_${Date.now()}`,
        name: shortName,
        lat,
        lng,
        distanceFromStart,
        type: 'route', // New stops are always intermediate
        isCustom: true,
        isAutoGenerated: false,
        order: stops.length - 1, // Will be recalculated by orderStopsCorrectly
      };

      // CRITICAL FIX: Insert new stop BEFORE the END stop to preserve END position
      // Find the END stop (must have type === 'end')
      const endStopIndex = stops.findIndex(s => s.type === 'end');
      
      let allStops: Stop[];
      if (endStopIndex >= 0) {
        // END stop exists - insert new stop BEFORE it
        allStops = [
          ...stops.slice(0, endStopIndex),
          newStop,
          ...stops.slice(endStopIndex)
        ];
      } else {
        // No explicit END stop - just append (fallback)
        allStops = [...stops, newStop];
      }
      
      // Re-order to ensure correct distance-based positioning while preserving START/END
      const orderedStops = orderStopsCorrectly(allStops);
      setStops(orderedStops);
      
      setMapSelectionMode(false);
      setSelectedMapPoint(null);
    } catch (error) {
      console.error('Reverse geocoding error:', error);
      setGeocodingError('Failed to get location name. Please try again.');
    } finally {
      setIsGeocodingStop(false);
    }
  };

  const handleAddStop = async () => {
    if (!newStopName.trim()) return;

    setIsGeocodingStop(true);
    setGeocodingError(null);

    try {
      // Geocode the stop name to get coordinates
      const response = await fetch(`/api/nominatim/search?q=${encodeURIComponent(newStopName)}&limit=1`);
      const data = await response.json();

      if (!Array.isArray(data) || data.length === 0) {
        setGeocodingError('Location not found. Please try a different name.');
        setIsGeocodingStop(false);
        return;
      }

      const location = data[0];
      const lat = parseFloat(location.lat);
      const lng = parseFloat(location.lon);

      // Validate the stop is on the route
      if (routeCoordinates && routeCoordinates.length > 0) {
        const isOnRoute = isPointNearPolyline({ lat, lng }, routeCoordinates, 500);
        if (!isOnRoute) {
          setGeocodingError('This location is not on the route. Please select a location along your route.');
          setIsGeocodingStop(false);
          return;
        }
      }

      // Calculate distance from starting point (first stop or route start)
      const startPoint = stops.length > 0 ? stops[0] : (routeCoordinates && routeCoordinates.length > 0 ? routeCoordinates[0] : null);
      let distanceFromStart = 0;

      if (startPoint) {
        distanceFromStart = haversine(startPoint, { lat, lng });
      }
      
      // CRITICAL: Cap distance to ensure new stop never exceeds END stop distance
      // This prevents new stops from accidentally becoming the END stop
      const endStop = stops.find(s => s.type === 'end');
      if (endStop && endStop.distanceFromStart && distanceFromStart > endStop.distanceFromStart) {
        // Set distance slightly less than END to maintain ordering
        distanceFromStart = endStop.distanceFromStart - 10; // 10 meters before END
      }

      const newStop: Stop = {
        id: `stop_${Date.now()}`,
        name: location.display_name.split(',')[0] || newStopName,
        lat,
        lng,
        distanceFromStart,
        type: 'route', // Use 'route' for consistency with map selection
        isCustom: true,
        isAutoGenerated: false,
        order: stops.length - 1, // Will be recalculated by orderStopsCorrectly
      };

      // CRITICAL FIX: Insert new stop BEFORE the END stop to preserve END position
      // Find the END stop (must have type === 'end')
      const endStopIndex = stops.findIndex(s => s.type === 'end');
      
      let allStops: Stop[];
      if (endStopIndex >= 0) {
        // END stop exists - insert new stop BEFORE it
        allStops = [
          ...stops.slice(0, endStopIndex),
          newStop,
          ...stops.slice(endStopIndex)
        ];
      } else {
        // No explicit END stop - just append (fallback)
        allStops = [...stops, newStop];
      }
      
      // Re-order to ensure correct distance-based positioning while preserving START/END
      const orderedStops = orderStopsCorrectly(allStops);
      setStops(orderedStops);
      
      setNewStopName('');
      setShowAddStop(false);
    } catch (error) {
      console.error('Geocoding error:', error);
      setGeocodingError('Failed to find location. Please try again.');
    } finally {
      setIsGeocodingStop(false);
    }
  };

  const handleSaveStops = async () => {
    if (!onUpdateStops) return;

    setIsSaving(true);
    try {
      await onUpdateStops(stops);
    } finally {
      setIsSaving(false);
    }
  };

  const formatDistance = (meters: number) => {
    if (meters < 1000) return `${meters}m`;
    return `${(meters / 1000).toFixed(1)}km`;
  };

  // Map click handler component
  function MapClickHandler() {
    useMapEvents({
      click: async (e) => {
        if (!mapSelectionMode || !routeCoordinates) return;
        
        const clickedPoint = { lat: e.latlng.lat, lng: e.latlng.lng };
        
        // Check if clicked point is near the route (within 500 meters)
        const isOnRoute = isPointNearPolyline(clickedPoint, routeCoordinates, 500);
        
        if (isOnRoute) {
          setSelectedMapPoint(clickedPoint);
          setSelectedPlaceName('Fetching location...');
          setGeocodingError(null);
          
          // Fetch place name
          try {
            const headers: HeadersInit = { 'Content-Type': 'application/json' };
            if (getAuthToken) {
              try {
                const token = await getAuthToken();
                if (token) headers['Authorization'] = `Bearer ${token}`;
              } catch (_) {}
            }
            const response = await fetch(`/api/nominatim/reverse?lat=${clickedPoint.lat}&lon=${clickedPoint.lng}`, { headers });
            const data = await response.json();
            const displayName = data.display_name || 'Unknown location';
            
            // Extract meaningful name
            const parts = displayName.split(',').map((p: string) => p.trim());
            let shortName = parts[0];
            
            if (parts.length > 1 && (/^\d+[a-z]?$/.test(shortName.trim()))) {
              shortName = `${parts[0]}, ${parts[1]}`;
            } else if (shortName.length < 3 && parts[1]?.length > 2) {
              shortName = `${parts[0]}, ${parts[1]}`;
            }
            
            setSelectedPlaceName(shortName);
          } catch (error) {
            console.error('Failed to fetch place name:', error);
            setSelectedPlaceName('Selected Location');
          }
        } else {
          setGeocodingError('Please click on or near the route line.');
          setSelectedMapPoint(null);
          setSelectedPlaceName(null);
        }
      },
    });
    return null;
  }

  // If no triggerText, show stops directly without dialog
  if (!triggerText) {
    return (
      <div className="flex flex-col w-full max-h-[80vh]">
        <DialogHeader className="flex-shrink-0">
          <DialogTitle>Route Stops ({stops.length})</DialogTitle>
        </DialogHeader>

        <div className="flex-1 overflow-y-auto space-y-2 pr-2">
          {/* Stops List */}
          <div className="space-y-2 overflow-y-auto">
            {stops.length === 0 ? (
              <div className="text-center py-8 text-muted-foreground">
                No stops available for this route
              </div>
            ) : (
              stops.map((stop, index) => {
                // Use stop.type to determine if it's START or END, not just position
                const isStartStop = stop.type === 'start';
                const isEndStop = stop.type === 'end';
                const isFixedStop = isStartStop || isEndStop;
                
                return (
                <div
                  key={getStopKey(stop, index)}
                  className={`p-3 border rounded-lg flex items-center gap-3 ${isFixedStop ? 'bg-muted/30' : ''}`}
                >
                  <div className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-semibold ${
                    isStartStop
                      ? 'bg-green-500 text-white' 
                      : isEndStop
                        ? 'bg-red-500 text-white'
                        : 'bg-primary text-primary-foreground'
                  }`}>
                    {index + 1}
                  </div>

                  <div className="flex-1 min-w-0">
                    {editingId === stop.id && isCreator && !isFixedStop ? (
                      <div className="flex gap-2">
                        <Input
                          value={editingName || ''}
                          onChange={(e) => setEditingName(e.target.value)}
                          placeholder="Stop name"
                          className="text-sm"
                        />
                        <Button
                          size="sm"
                          onClick={() =>
                            handleRenameStop(stop.id, editingName)
                          }
                        >
                          Save
                        </Button>
                      </div>
                    ) : (
                      <div>
                        <div className="font-semibold text-sm flex items-center gap-2">
                          {needsNameLookup(stop.name) ? (
                            <span className="text-muted-foreground flex items-center gap-1">
                              <Loader2 className="w-3 h-3 animate-spin" />
                              Fetching name...
                            </span>
                          ) : (
                            cleanLocationName(stop.name)
                          )}
                          {isStartStop && (
                            <Badge className="text-xs bg-green-500 text-white">START</Badge>
                          )}
                          {isEndStop && (
                            <Badge className="text-xs bg-red-500 text-white">END</Badge>
                          )}
                        </div>
                        <div className="text-xs text-muted-foreground">
                          {formatDistance(stop.distanceFromStart)} from start
                          {(isStartStop || isEndStop) && universityDisplay && (
                            <React.Fragment key={`uni-display-${stop.id}`}>
                              {' • '}
                              <span className="font-semibold text-primary bg-primary/10 px-2 py-0.5 rounded">
                                {universityDisplay}
                              </span>
                            </React.Fragment>
                          )}
                          {!isFixedStop && ' • route'}
                          {isFixedStop && ' • Fixed'}
                        </div>
                      </div>
                    )}
                  </div>

                  <div className="flex items-center gap-2">
                    <Badge variant="outline" className="text-xs">
                      {stop.isAutoGenerated ? 'Auto' : 'Custom'}
                    </Badge>

                    {isCreator && !isFixedStop && (
                      <div className="flex gap-2">
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => {
                            setEditingId(stop.id);
                            setEditingName(stop.name);
                          }}
                        >
                          <Edit2 className="w-3 h-3" />
                        </Button>

                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => handleRemoveStop(stop.id)}
                        >
                          <X className="w-4 h-4 text-destructive" />
                        </Button>
                      </div>
                    )}
                  </div>
                </div>
              );
              })
            )}
          </div>

          {/* Add Stop Section (Creator Only) */}
          {isCreator && (
            <div className="border-t pt-4">
              {mapSelectionMode ? (
                <div className="space-y-3 p-3 border rounded-lg bg-blue-50">
                  <div className="flex items-center gap-2">
                    <MousePointer2 className="w-4 h-4 text-blue-600" />
                    <p className="text-sm font-medium text-blue-900">
                      Click on the route map below to select a stop location
                    </p>
                  </div>
                  {selectedMapPoint && selectedPlaceName && (
                    <div className="text-xs text-muted-foreground">
                      Selected: {selectedPlaceName}
                    </div>
                  )}
                  {geocodingError && (
                    <p className="text-sm text-destructive">{geocodingError}</p>
                  )}
                  <div className="flex gap-2">
                    <Button 
                      size="sm" 
                      onClick={() => selectedMapPoint && handleAddStopFromMap(selectedMapPoint.lat, selectedMapPoint.lng)}
                      disabled={!selectedMapPoint || isGeocodingStop}
                    >
                      {isGeocodingStop ? (
                        <>
                          <Loader2 className="w-3 h-3 mr-2 animate-spin" />
                          Adding...
                        </>
                      ) : (
                        'Add Selected Stop'
                      )}
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => {
                        setMapSelectionMode(false);
                        setSelectedMapPoint(null);
                        setSelectedPlaceName(null);
                        setGeocodingError(null);
                      }}
                      disabled={isGeocodingStop}
                    >
                      Cancel
                    </Button>
                  </div>
                </div>
              ) : showAddStop ? (
                <div className="space-y-3 p-3 border rounded-lg bg-slate-50">
                  <div className="space-y-2">
                    <Input
                      placeholder="Enter stop name or address (e.g., University Road, Main Market)"
                      value={newStopName || ''}
                      onChange={(e) => {
                        setNewStopName(e.target.value);
                        setGeocodingError(null);
                      }}
                      onKeyDown={(e) => {
                        if (e.key === 'Enter' && !isGeocodingStop) {
                          handleAddStop();
                        }
                      }}
                      disabled={isGeocodingStop}
                    />
                    {geocodingError && (
                      <p className="text-sm text-destructive">{geocodingError}</p>
                    )}
                    <p className="text-xs text-muted-foreground">
                      Stop will be automatically positioned and sorted by distance from start
                    </p>
                  </div>
                  <div className="flex gap-2">
                    <Button 
                      size="sm" 
                      onClick={handleAddStop}
                      disabled={isGeocodingStop || !newStopName.trim()}
                    >
                      {isGeocodingStop ? (
                        <>
                          <Loader2 className="w-3 h-3 mr-2 animate-spin" />
                          Finding location...
                        </>
                      ) : (
                        'Add Stop'
                      )}
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => {
                        setShowAddStop(false);
                        setNewStopName('');
                        setGeocodingError(null);
                      }}
                      disabled={isGeocodingStop}
                    >
                      Cancel
                    </Button>
                  </div>
                </div>
              ) : (
                <div className="flex gap-2">
                  <Button
                    variant="outline"
                    className="flex-1 gap-2"
                    onClick={() => setShowAddStop(true)}
                  >
                    <Plus className="w-4 h-4" />
                    Add by Name
                  </Button>
                  <Button
                    variant="outline"
                    className="flex-1 gap-2"
                    onClick={() => setMapSelectionMode(true)}
                    disabled={!routeCoordinates || routeCoordinates.length === 0}
                  >
                    <MousePointer2 className="w-4 h-4" />
                    Select on Map
                  </Button>
                </div>
              )}
            </div>
          )}

          {/* Save Changes */}
          {isCreator && onUpdateStops && (
            <Button
              type="button"
              onClick={handleSaveStops}
              disabled={isSaving}
              className="w-full"
            >
              {isSaving ? 'Saving...' : 'Save Changes'}
            </Button>
          )}

          {/* Map Preview */}
          {stopsWithCoords.length > 0 && routeCoordinates && routeCoordinates.length > 0 && (
            <div className="border rounded-lg overflow-hidden flex-shrink-0" style={{ height: '250px' }}>
              <Suspense fallback={<div className="h-full w-full flex items-center justify-center bg-slate-900/50"><div className="text-slate-400">Loading map...</div></div>}>
                <MapContainer
                  bounds={getBoundsFromPoints(stopsWithCoords.map((s) => ({ lat: Number(s.lat), lng: Number(s.lng) })))}
                  style={{ height: '100%', width: '100%', cursor: mapSelectionMode ? 'crosshair' : 'grab' }}
                >
                <TileLayer
                  url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                  attribution='&copy; OpenStreetMap contributors'
                />

                <MapClickHandler />

                {/* Show route polyline */}
                {routeCoordinates && routeCoordinates.length > 0 && (
                  <>
                    <Polyline
                      key="route-polyline-outline"
                      positions={routeCoordinates.map(c => [c.lat, c.lng])}
                      color="#ffffff"
                      weight={6}
                      opacity={0.5}
                    />
                    <Polyline
                      key="route-polyline"
                      positions={routeCoordinates.map(c => [c.lat, c.lng])}
                      color="#60A5FA"
                      weight={3}
                      opacity={0.8}
                    />
                  </>
                )}

                {/* Show selected point marker */}
                {selectedMapPoint && mapSelectionMode && (
                  <Marker position={[selectedMapPoint.lat, selectedMapPoint.lng]}>
                    <Popup>Selected location</Popup>
                  </Marker>
                )}

                {stopsWithCoords.map((stop, idx) => (
                  <Marker
                    key={stop.id || `marker-${idx}`}
                    position={[Number(stop.lat), Number(stop.lng)]}
                  >
                    <Popup>
                      <strong>{cleanLocationName(stop.name)}</strong>
                      <br/>
                      {stop.isAutoGenerated ? 'Auto' : 'Custom'}
                    </Popup>
                    <Tooltip>
                      {idx === 0 ? 'Start' : idx === stopsWithCoords.length - 1 ? 'End' : `Stop ${idx + 1}`}
                    </Tooltip>
                  </Marker>
                ))}
              </MapContainer>
              </Suspense>
            </div>
          )}

          {/* ===== FIX: Show selected point and confirmation buttons when map selection is active =====*/}
          {mapSelectionMode && selectedMapPoint && selectedPlaceName && (
            <div className="p-3 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg">
              <div className="text-sm font-semibold mb-2">📍 Selected Location:</div>
              <div className="text-sm text-blue-900 dark:text-blue-100 mb-3 font-medium">{selectedPlaceName}</div>
              <div className="flex gap-2">
                <Button
                  size="sm"
                  onClick={() => {
                    if (!selectedMapPoint) return;
                    handleAddStopFromMap(selectedMapPoint.lat, selectedMapPoint.lng);
                  }}
                  className="flex-1"
                >
                  ✅ Add This Stop
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => {
                    setSelectedMapPoint(null);
                    setSelectedPlaceName(null);
                    setMapSelectionMode(false);
                  }}
                  className="flex-1"
                >
                  ✕ Cancel
                </Button>
              </div>
            </div>
          )}

        {/* Request Ride Button - for non-creators */}
        {!isCreator && onRequestRide && (
          <div className="flex gap-2 pt-4 border-t flex-shrink-0">
            <button
              onClick={onRequestRide}
              className="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded-md transition"
            >
              Request Ride
            </button>
          </div>
        )}
        </div>
      </div>
    );
  }

  // Show with trigger button in Dialog
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline" className="gap-2">
          <MapPin className="w-4 h-4" />
          {triggerText}
        </Button>
      </DialogTrigger>

      <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto z-[9999]">
        <DialogHeader>
          <DialogTitle>Route Stops ({stops.length})</DialogTitle>
        </DialogHeader>
        <p className="sr-only" id="stops-dialog-desc">Stops list and map preview for this route.</p>

        <div className="space-y-4">
          {/* Stops List */}
          <div className="space-y-2">
            {stops.length === 0 ? (
              <div className="text-center py-8 text-muted-foreground">
                No stops available for this route
              </div>
            ) : (
              stops.map((stop, index) => {
                // Use stop.type to determine if it's START or END, not just position
                const isStartStop = stop.type === 'start';
                const isEndStop = stop.type === 'end';
                const isFixedStop = isStartStop || isEndStop;
                
                return (
                  <div
                    key={getStopKey(stop, index)}
                    className={`p-3 border rounded-lg flex items-center gap-3 ${isFixedStop ? 'bg-muted/30' : ''}`}
                  >
                  <div className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-semibold ${
                    isStartStop
                      ? 'bg-green-500 text-white' 
                      : isEndStop
                        ? 'bg-red-500 text-white'
                        : 'bg-primary text-primary-foreground'
                  }`}>
                    {index + 1}
                  </div>

                  <div className="flex-1 min-w-0">
                    {editingId === stop.id && isCreator && !isFixedStop ? (
                      <div className="flex gap-2">
                        <Input
                          value={editingName || ''}
                          onChange={(e) => setEditingName(e.target.value)}
                          placeholder="Stop name"
                          className="text-sm"
                        />
                        <Button
                          size="sm"
                          onClick={() =>
                            handleRenameStop(stop.id, editingName)
                          }
                        >
                          Save
                        </Button>
                      </div>
                    ) : (
                      <div>
                        <div className="font-semibold text-sm flex items-center gap-2">
                          {needsNameLookup(stop.name) ? (
                            <span className="text-muted-foreground flex items-center gap-1">
                              <Loader2 className="w-3 h-3 animate-spin" />
                              Fetching name...
                            </span>
                          ) : (
                            cleanLocationName(stop.name)
                          )}
                          {isStartStop && (
                            <Badge className="text-xs bg-green-500 text-white">START</Badge>
                          )}
                          {isEndStop && (
                            <Badge className="text-xs bg-red-500 text-white">END</Badge>
                          )}
                        </div>
                        <div className="text-xs text-muted-foreground">
                          {formatDistance(stop.distanceFromStart)} from start
                          {(isStartStop || isEndStop) && universityDisplay && (
                            <React.Fragment key={`uni-display-2-${stop.id}`}>
                              {' • '}
                              <span className="font-semibold text-primary bg-primary/10 px-2 py-0.5 rounded">
                                {universityDisplay}
                              </span>
                            </React.Fragment>
                          )}
                          {!isFixedStop && ' • route'}
                          {isFixedStop && ' • Fixed'}
                        </div>
                      </div>
                    )}
                  </div>

                  <div className="flex items-center gap-2">
                    <Badge variant="outline" className="text-xs">
                      {stop.isAutoGenerated ? 'Auto' : 'Custom'}
                    </Badge>

                    {isCreator && !isFixedStop && (
                      <>
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => {
                            setEditingId(stop.id);
                            setEditingName(stop.name);
                          }}
                        >
                          <Edit2 className="w-4 h-4" />
                        </Button>
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => handleRemoveStop(stop.id)}
                        >
                          <X className="w-4 h-4" />
                        </Button>
                      </>
                    )}
                  </div>
                </div>
                );
              })
            )}
          </div>

          {/* Add Stop Section - only for creators */}
          {isCreator && (
            <div className="border rounded-lg p-4 space-y-3">
              <div className="font-semibold">Add Stop</div>
              {showAddStop ? (
                <div className="space-y-2">
                  <Input
                    value={newStopName}
                    onChange={(e) => setNewStopName(e.target.value)}
                    placeholder="Enter stop name"
                    className="text-sm"
                  />
                  <div className="flex gap-2">
                    <Button
                      size="sm"
                      onClick={handleAddStop}
                      disabled={isGeocodingStop}
                    >
                      {isGeocodingStop ? 'Searching...' : 'Search & Add'}
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => setShowAddStop(false)}
                    >
                      Cancel
                    </Button>
                  </div>
                  {geocodingError && (
                    <div className="text-xs text-red-600">{geocodingError}</div>
                  )}
                </div>
              ) : (
                <Button
                  size="sm"
                  className="gap-2"
                  onClick={() => setShowAddStop(true)}
                >
                  <Plus className="w-4 h-4" />
                  Search by Name
                </Button>
              )}
              <Button
                size="sm"
                variant="outline"
                className="w-full gap-2"
                onClick={() => setMapSelectionMode(!mapSelectionMode)}
              >
                <MousePointer2 className="w-4 h-4" />
                {mapSelectionMode ? 'Cancel Map Selection' : 'Select from Map'}
              </Button>
            </div>
          )}

          {/* Selected Location Confirmation - when map selection is active */}
          {mapSelectionMode && selectedMapPoint && selectedPlaceName && (
            <div className="bg-blue-50 dark:bg-blue-950 border border-blue-200 dark:border-blue-800 rounded-lg p-4 space-y-3">
              <div className="text-sm text-blue-900 dark:text-blue-100 mb-3 font-medium">{selectedPlaceName}</div>
              <div className="flex gap-2">
                <Button
                  size="sm"
                  className="flex-1"
                  onClick={() => {
                    if (!selectedMapPoint) return;
                    handleAddStopFromMap(selectedMapPoint.lat, selectedMapPoint.lng);
                  }}
                >
                  ✅ Add This Stop
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => {
                    setSelectedMapPoint(null);
                    setSelectedPlaceName(null);
                    setMapSelectionMode(false);
                  }}
                  className="flex-1"
                >
                  ✕ Cancel
                </Button>
              </div>
            </div>
          )}

          {/* Map Display */}
          {routeCoordinates && routeCoordinates.length > 0 && (
            <div className="border rounded-lg overflow-hidden h-64">
              <Suspense fallback={<div className="h-full w-full flex items-center justify-center bg-slate-900/50"><div className="text-slate-400">Loading map...</div></div>}>
              <MapContainer
                bounds={getBoundsFromPoints(routeCoordinates.map((point) => ({ lat: Number(point.lat), lng: Number(point.lng) })))}
                style={{ height: '100%', width: '100%' }}
              >
                <TileLayer
                  url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                  attribution='&copy; OpenStreetMap contributors'
                />
                <>
                  <Polyline
                    positions={routeCoordinates.map((point) => [point.lat, point.lng])}
                    color="#ffffff"
                    weight={7}
                    opacity={0.5}
                  />
                  <Polyline
                    positions={routeCoordinates.map((point) => [point.lat, point.lng])}
                    color="#60A5FA"
                    weight={4}
                    opacity={0.8}
                  />
                </>
                <MapClickHandler />
                {selectedMapPoint && (
                  <Marker position={[selectedMapPoint.lat, selectedMapPoint.lng]}>
                    <Popup>{selectedPlaceName || 'Selected Point'}</Popup>
                  </Marker>
                )}
                {stopsWithCoords.map((stop, idx) => (
                  <Marker key={stop.id || `marker-${idx}`} position={[Number(stop.lat), Number(stop.lng)]}>
                    <Popup>{cleanLocationName(stop.name)}</Popup>
                  </Marker>
                ))}
              </MapContainer>
              </Suspense>
            </div>
          )}

          {/* Request Ride Button - for non-creators */}
          {!isCreator && onRequestRide && (
            <div className="flex gap-2 pt-4 border-t">
              <button
                onClick={onRequestRide}
                className="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded-md transition"
              >
                Request Ride
              </button>
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
