'use client';

import React, { useState, useCallback, useRef } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { MapPin, Plus, X, Edit2, Loader2, MousePointer2 } from 'lucide-react';
import { MapContainer, TileLayer, Marker, Popup, Polyline, useMapEvents } from '@/components/map';
import L from 'leaflet';
import { isPointNearPolyline, haversine, type LatLng } from '@/lib/route';
import { deduplicateByName } from '@/lib/stopFiltering';

interface Stop {
  id: string;
  name: string;
  lat: number;
  lng: number;
  distanceFromStart: number;
  type: string;
  isCustom: boolean;
  isAutoGenerated: boolean;
  order: number;
}

interface StopsViewerProps {
  stops: Stop[];
  routePolyline?: string;
  routeCoordinates?: LatLng[];
  isCreator?: boolean;
  onUpdateStops?: (stops: Stop[]) => Promise<void>;
  triggerText?: string;
}

export default function StopsViewer({
  stops: initialStops,
  routePolyline,
  routeCoordinates,
  isCreator = false,
  onUpdateStops,
  triggerText = 'View Stops',
}: StopsViewerProps) {
  const [stops, setStops] = useState<Stop[]>(initialStops);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editingName, setEditingName] = useState('');
  const [showAddStop, setShowAddStop] = useState(false);
  const [newStopName, setNewStopName] = useState('');
  const [isSaving, setIsSaving] = useState(false);
  const [isGeocodingStop, setIsGeocodingStop] = useState(false);
  const [geocodingError, setGeocodingError] = useState<string | null>(null);
  const [mapSelectionMode, setMapSelectionMode] = useState(false);
  const [selectedMapPoint, setSelectedMapPoint] = useState<LatLng | null>(null);
  const [selectedPlaceName, setSelectedPlaceName] = useState<string | null>(null);
  const [isFetchingNames, setIsFetchingNames] = useState(false);

  // Fetch names for stops that don't have meaningful names
  React.useEffect(() => {
    const fetchMissingNames = async () => {
      // Check if any stops need names fetched (have generic names like "Stop 1", "Stop 2", etc.)
      const stopsNeedingNames = stops.filter(stop => 
        !stop.name || /^(Stop|Location|Loading)\s*\d+$/i.test(stop.name.trim())
      );

      if (stopsNeedingNames.length === 0 || isFetchingNames) return;

      console.log('Fetching names for', stopsNeedingNames.length, 'stops without meaningful names');
      setIsFetchingNames(true);

      try {
        const updatedStops = [...stops];
        
        for (let i = 0; i < stopsNeedingNames.length; i++) {
          const stop = stopsNeedingNames[i];
          const stopIndex = stops.findIndex(s => s.id === stop.id);
          
          if (stopIndex === -1) continue;

          try {
            await new Promise(resolve => setTimeout(resolve, i * 150)); // Rate limiting
            
            const res = await fetch(`/api/nominatim/reverse?lat=${stop.lat}&lon=${stop.lng}`);
            if (res.ok) {
              const data = await res.json();
              if (data.display_name) {
                // Extract meaningful name from display_name
                const parts = data.display_name.split(',').map((p: string) => p.trim());
                let shortName = parts[0];
                
                if (parts.length > 1 && (/^\d+[a-z]?$/.test(shortName.trim()))) {
                  shortName = `${parts[0]}, ${parts[1]}`;
                } else if (shortName.length < 3 && parts[1]?.length > 2) {
                  shortName = `${parts[0]}, ${parts[1]}`;
                }
                
                updatedStops[stopIndex] = { ...updatedStops[stopIndex], name: shortName };
                console.log(`Fetched name for stop ${stopIndex + 1}:`, shortName);
              }
            }
          } catch (error) {
            console.error(`Failed to fetch name for stop at index ${stopIndex}:`, error);
          }
        }
        
        // Remove consecutive duplicate names (e.g., "National Highway" appearing multiple times)
        const deduplicatedStops = deduplicateByName(updatedStops);
        
        setStops(deduplicatedStops);
        console.log('Finished fetching stop names. Final count after deduplication:', deduplicatedStops.length);
      } catch (error) {
        console.error('Error fetching stop names:', error);
      } finally {
        setIsFetchingNames(false);
      }
    };

    fetchMissingNames();
  }, [initialStops]); // Re-run if initialStops change

  const handleRemoveStop = (id: string) => {
    setStops(stops.filter((s) => s.id !== id));
  };

  const handleRenameStop = (id: string, newName: string) => {
    setStops(
      stops.map((s) => (s.id === id ? { ...s, name: newName } : s))
    );
    setEditingId(null);
  };

  const handleAddStopFromMap = async (lat: number, lng: number) => {
    setIsGeocodingStop(true);
    setGeocodingError(null);

    try {
      // Reverse geocode to get the name
      const response = await fetch(`/api/nominatim/reverse?lat=${lat}&lon=${lng}`);
      const data = await response.json();

      const displayName = data.display_name || 'Custom Stop';
      // Import the extractMeaningfulStopName function
      const parts = displayName.split(',').map((p: string) => p.trim());
      let shortName = parts[0];
      
      // Extract meaningful name
      if (parts.length > 1 && (/^\d+[a-z]?$/.test(shortName.trim()))) {
        shortName = `${parts[0]}, ${parts[1]}`;
      } else if (shortName.length < 3 && parts[1]?.length > 2) {
        shortName = `${parts[0]}, ${parts[1]}`;
      }

      // Calculate distance from starting point
      const startPoint = stops.length > 0 ? stops[0] : (routeCoordinates && routeCoordinates.length > 0 ? routeCoordinates[0] : null);
      let distanceFromStart = 0;

      if (startPoint) {
        distanceFromStart = haversine(startPoint, { lat, lng });
      }

      const newStop: Stop = {
        id: `stop_${Date.now()}`,
        name: shortName,
        lat,
        lng,
        distanceFromStart,
        type: 'custom',
        isCustom: true,
        isAutoGenerated: false,
        order: stops.length,
      };

      // Add the new stop and sort all stops by distance from start
      const updatedStops = [...stops, newStop].sort((a, b) => a.distanceFromStart - b.distanceFromStart);
      const sortedStops = updatedStops.map((stop, idx) => ({ ...stop, order: idx }));
      
      setStops(sortedStops);
      setMapSelectionMode(false);
      setSelectedMapPoint(null);
    } catch (error) {
      console.error('Reverse geocoding error:', error);
      setGeocodingError('Failed to get location name. Please try again.');
    } finally {
      setIsGeocodingStop(false);
    }
  };

  const handleAddStop = async () => {
    if (!newStopName.trim()) return;

    setIsGeocodingStop(true);
    setGeocodingError(null);

    try {
      // Geocode the stop name to get coordinates
      const response = await fetch(`/api/nominatim/search?q=${encodeURIComponent(newStopName)}&limit=1`);
      const data = await response.json();

      if (!Array.isArray(data) || data.length === 0) {
        setGeocodingError('Location not found. Please try a different name.');
        setIsGeocodingStop(false);
        return;
      }

      const location = data[0];
      const lat = parseFloat(location.lat);
      const lng = parseFloat(location.lon);

      // Validate the stop is on the route
      if (routeCoordinates && routeCoordinates.length > 0) {
        const isOnRoute = isPointNearPolyline({ lat, lng }, routeCoordinates, 500);
        if (!isOnRoute) {
          setGeocodingError('This location is not on the route. Please select a location along your route.');
          setIsGeocodingStop(false);
          return;
        }
      }

      // Calculate distance from starting point (first stop or route start)
      const startPoint = stops.length > 0 ? stops[0] : (routeCoordinates && routeCoordinates.length > 0 ? routeCoordinates[0] : null);
      let distanceFromStart = 0;

      if (startPoint) {
        distanceFromStart = haversine(startPoint, { lat, lng });
      }

      const newStop: Stop = {
        id: `stop_${Date.now()}`,
        name: location.display_name.split(',')[0] || newStopName,
        lat,
        lng,
        distanceFromStart,
        type: 'custom',
        isCustom: true,
        isAutoGenerated: false,
        order: stops.length,
      };

      // Add the new stop and sort all stops by distance from start
      const updatedStops = [...stops, newStop].sort((a, b) => a.distanceFromStart - b.distanceFromStart);
      
      // Update order property after sorting
      const sortedStops = updatedStops.map((stop, idx) => ({ ...stop, order: idx }));
      
      setStops(sortedStops);
      setNewStopName('');
      setShowAddStop(false);
    } catch (error) {
      console.error('Geocoding error:', error);
      setGeocodingError('Failed to find location. Please try again.');
    } finally {
      setIsGeocodingStop(false);
    }
  };

  const handleSaveStops = async () => {
    if (!onUpdateStops) return;

    setIsSaving(true);
    try {
      await onUpdateStops(stops);
    } finally {
      setIsSaving(false);
    }
  };

  const formatDistance = (meters: number) => {
    if (meters < 1000) return `${meters}m`;
    return `${(meters / 1000).toFixed(1)}km`;
  };

  // Map click handler component
  function MapClickHandler() {
    useMapEvents({
      click: async (e) => {
        if (!mapSelectionMode || !routeCoordinates) return;
        
        const clickedPoint = { lat: e.latlng.lat, lng: e.latlng.lng };
        
        // Check if clicked point is near the route (within 500 meters)
        const isOnRoute = isPointNearPolyline(clickedPoint, routeCoordinates, 500);
        
        if (isOnRoute) {
          setSelectedMapPoint(clickedPoint);
          setSelectedPlaceName('Fetching location...');
          setGeocodingError(null);
          
          // Fetch place name
          try {
            const response = await fetch(`/api/nominatim/reverse?lat=${clickedPoint.lat}&lon=${clickedPoint.lng}`);
            const data = await response.json();
            const displayName = data.display_name || 'Unknown location';
            
            // Extract meaningful name
            const parts = displayName.split(',').map((p: string) => p.trim());
            let shortName = parts[0];
            
            if (parts.length > 1 && (/^\d+[a-z]?$/.test(shortName.trim()))) {
              shortName = `${parts[0]}, ${parts[1]}`;
            } else if (shortName.length < 3 && parts[1]?.length > 2) {
              shortName = `${parts[0]}, ${parts[1]}`;
            }
            
            setSelectedPlaceName(shortName);
          } catch (error) {
            console.error('Failed to fetch place name:', error);
            setSelectedPlaceName(`${clickedPoint.lat.toFixed(6)}, ${clickedPoint.lng.toFixed(6)}`);
          }
        } else {
          setGeocodingError('Please click on or near the route line.');
          setSelectedMapPoint(null);
          setSelectedPlaceName(null);
        }
      },
    });
    return null;
  }

  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline" className="gap-2">
          <MapPin className="w-4 h-4" />
          {triggerText}
        </Button>
      </DialogTrigger>

      <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto z-[9999]">
        <DialogHeader>
          <DialogTitle>Route Stops ({stops.length})</DialogTitle>
        </DialogHeader>

        <div className="space-y-4">
          {/* Stops List */}
          <div className="space-y-2">
            {stops.length === 0 ? (
              <div className="text-center py-8 text-muted-foreground">
                No stops available for this route
              </div>
            ) : (
              stops.map((stop, index) => {
                const isFirstStop = index === 0;
                const isLastStop = index === stops.length - 1;
                const isFixedStop = isFirstStop || isLastStop;
                
                return (
                <div
                  key={stop.id}
                  className={`p-3 border rounded-lg flex items-center gap-3 ${isFixedStop ? 'bg-muted/30' : ''}`}
                >
                  <div className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-semibold ${
                    isFixedStop 
                      ? 'bg-amber-500 text-white' 
                      : 'bg-primary text-primary-foreground'
                  }`}>
                    {index + 1}
                  </div>

                  <div className="flex-1 min-w-0">
                    {editingId === stop.id && isCreator && !isFixedStop ? (
                      <div className="flex gap-2">
                        <Input
                          value={editingName || ''}
                          onChange={(e) => setEditingName(e.target.value)}
                          placeholder="Stop name"
                          className="text-sm"
                        />
                        <Button
                          size="sm"
                          onClick={() =>
                            handleRenameStop(stop.id, editingName)
                          }
                        >
                          Save
                        </Button>
                      </div>
                    ) : (
                      <div>
                        <div className="font-semibold text-sm flex items-center gap-2">
                          {stop.name}
                          {isFirstStop && (
                            <Badge className="text-xs" variant="secondary">START</Badge>
                          )}
                          {isLastStop && (
                            <Badge className="text-xs" variant="secondary">END</Badge>
                          )}
                        </div>
                        <div className="text-xs text-muted-foreground">
                          {formatDistance(stop.distanceFromStart)} from start • {stop.type}
                          {isFixedStop && ' • Fixed'}
                        </div>
                      </div>
                    )}
                  </div>

                  <div className="flex items-center gap-2">
                    <Badge variant="outline" className="text-xs">
                      {stop.isAutoGenerated ? 'Auto' : 'Custom'}
                    </Badge>

                    {isCreator && !isFixedStop && (
                      <>
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => {
                            setEditingId(stop.id);
                            setEditingName(stop.name);
                          }}
                        >
                          <Edit2 className="w-3 h-3" />
                        </Button>

                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => handleRemoveStop(stop.id)}
                        >
                          <X className="w-4 h-4 text-destructive" />
                        </Button>
                      </>
                    )}
                  </div>
                </div>
              );
              })
            )}
          </div>

          {/* Add Stop Section (Creator Only) */}
          {isCreator && (
            <div className="border-t pt-4">
              {mapSelectionMode ? (
                <div className="space-y-3 p-3 border rounded-lg bg-blue-50">
                  <div className="flex items-center gap-2">
                    <MousePointer2 className="w-4 h-4 text-blue-600" />
                    <p className="text-sm font-medium text-blue-900">
                      Click on the route map below to select a stop location
                    </p>
                  </div>
                  {selectedMapPoint && selectedPlaceName && (
                    <div className="text-xs text-muted-foreground">
                      Selected: {selectedPlaceName}
                    </div>
                  )}
                  {geocodingError && (
                    <p className="text-sm text-destructive">{geocodingError}</p>
                  )}
                  <div className="flex gap-2">
                    <Button 
                      size="sm" 
                      onClick={() => selectedMapPoint && handleAddStopFromMap(selectedMapPoint.lat, selectedMapPoint.lng)}
                      disabled={!selectedMapPoint || isGeocodingStop}
                    >
                      {isGeocodingStop ? (
                        <>
                          <Loader2 className="w-3 h-3 mr-2 animate-spin" />
                          Adding...
                        </>
                      ) : (
                        'Add Selected Stop'
                      )}
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => {
                        setMapSelectionMode(false);
                        setSelectedMapPoint(null);
                        setSelectedPlaceName(null);
                        setGeocodingError(null);
                      }}
                      disabled={isGeocodingStop}
                    >
                      Cancel
                    </Button>
                  </div>
                </div>
              ) : showAddStop ? (
                <div className="space-y-3 p-3 border rounded-lg bg-slate-50">
                  <div className="space-y-2">
                    <Input
                      placeholder="Enter stop name or address (e.g., University Road, Main Market)"
                      value={newStopName || ''}
                      onChange={(e) => {
                        setNewStopName(e.target.value);
                        setGeocodingError(null);
                      }}
                      onKeyDown={(e) => {
                        if (e.key === 'Enter' && !isGeocodingStop) {
                          handleAddStop();
                        }
                      }}
                      disabled={isGeocodingStop}
                    />
                    {geocodingError && (
                      <p className="text-sm text-destructive">{geocodingError}</p>
                    )}
                    <p className="text-xs text-muted-foreground">
                      Stop will be automatically positioned and sorted by distance from start
                    </p>
                  </div>
                  <div className="flex gap-2">
                    <Button 
                      size="sm" 
                      onClick={handleAddStop}
                      disabled={isGeocodingStop || !newStopName.trim()}
                    >
                      {isGeocodingStop ? (
                        <>
                          <Loader2 className="w-3 h-3 mr-2 animate-spin" />
                          Finding location...
                        </>
                      ) : (
                        'Add Stop'
                      )}
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => {
                        setShowAddStop(false);
                        setNewStopName('');
                        setGeocodingError(null);
                      }}
                      disabled={isGeocodingStop}
                    >
                      Cancel
                    </Button>
                  </div>
                </div>
              ) : (
                <div className="flex gap-2">
                  <Button
                    variant="outline"
                    className="flex-1 gap-2"
                    onClick={() => setShowAddStop(true)}
                  >
                    <Plus className="w-4 h-4" />
                    Add by Name
                  </Button>
                  <Button
                    variant="outline"
                    className="flex-1 gap-2"
                    onClick={() => setMapSelectionMode(true)}
                    disabled={!routeCoordinates || routeCoordinates.length === 0}
                  >
                    <MousePointer2 className="w-4 h-4" />
                    Select on Map
                  </Button>
                </div>
              )}
            </div>
          )}

          {/* Save Changes */}
          {isCreator && onUpdateStops && (
            <Button
              onClick={handleSaveStops}
              disabled={isSaving}
              className="w-full"
            >
              {isSaving ? 'Saving...' : 'Save Changes'}
            </Button>
          )}

          {/* Map Preview */}
          {stops.length > 0 && routePolyline && (
            <div className="border rounded-lg overflow-hidden">
              <MapContainer
                bounds={L.latLngBounds(
                  stops.map((s) => [s.lat, s.lng])
                )}
                style={{ height: '300px', cursor: mapSelectionMode ? 'crosshair' : 'grab' }}
              >
                <TileLayer
                  url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                  attribution='&copy; OpenStreetMap contributors'
                />

                <MapClickHandler />

                {/* Show route polyline */}
                {routeCoordinates && routeCoordinates.length > 0 && (
                  <Polyline
                    positions={routeCoordinates.map(c => [c.lat, c.lng])}
                    color="#ffffff"
                    weight={2}
                    opacity={0.9}
                    dashArray="5,5"
                  />
                )}

                {/* Show selected point marker */}
                {selectedMapPoint && mapSelectionMode && (
                  <Marker
                    position={[selectedMapPoint.lat, selectedMapPoint.lng]}
                    icon={L.icon({
                      iconUrl: 'https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-orange.png',
                      shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-shadow.png',
                      iconSize: [25, 41],
                      iconAnchor: [12, 41],
                      popupAnchor: [1, -34],
                      shadowSize: [41, 41]
                    })}
                  >
                    <Popup>Selected location</Popup>
                  </Marker>
                )}

                {stops.map((stop) => (
                  <Marker
                    key={stop.id}
                    position={[stop.lat, stop.lng]}
                    icon={
                      stop.isAutoGenerated
                        ? L.icon({
                            iconUrl: 'https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-blue.png',
                            shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-shadow.png',
                            iconSize: [25, 41],
                            iconAnchor: [12, 41],
                            popupAnchor: [1, -34],
                            shadowSize: [41, 41]
                          })
                        : L.icon({
                            iconUrl: 'https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-green.png',
                            shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-shadow.png',
                            iconSize: [25, 41],
                            iconAnchor: [12, 41],
                            popupAnchor: [1, -34],
                            shadowSize: [41, 41]
                          })
                    }
                  >
                    <Popup>{stop.name}</Popup>
                  </Marker>
                ))}
              </MapContainer>
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
